// Code generated by Fern. DO NOT EDIT.

package wallets

import (
	context "context"
	sdk "github.com/maximiseai/enrich-go-sdk"
	core "github.com/maximiseai/enrich-go-sdk/core"
	internal "github.com/maximiseai/enrich-go-sdk/internal"
	option "github.com/maximiseai/enrich-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Returns the current credit balance for your organization.
func (c *Client) GetWalletBalance(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.WalletBalanceResponse, error) {
	response, err := c.WithRawResponse.GetWalletBalance(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Browse your credit transactions — top-ups, deductions, refunds, and
// adjustments. Use the `type` parameter to filter by transaction type.
// Results are paginated.
func (c *Client) GetWalletTransactions(
	ctx context.Context,
	request *sdk.GetWalletTransactionsRequest,
	opts ...option.RequestOption,
) (*sdk.WalletTransactionsResponse, error) {
	response, err := c.WithRawResponse.GetWalletTransactions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
