// Code generated by Fern. DO NOT EDIT.

package client

import (
	companyfollowers "github.com/maximiseai/enrich-go-sdk/companyfollowers"
	core "github.com/maximiseai/enrich-go-sdk/core"
	emailfinder "github.com/maximiseai/enrich-go-sdk/emailfinder"
	emailvalidation "github.com/maximiseai/enrich-go-sdk/emailvalidation"
	internal "github.com/maximiseai/enrich-go-sdk/internal"
	leadfinder "github.com/maximiseai/enrich-go-sdk/leadfinder"
	option "github.com/maximiseai/enrich-go-sdk/option"
	peoplesearch "github.com/maximiseai/enrich-go-sdk/peoplesearch"
	phonefinder "github.com/maximiseai/enrich-go-sdk/phonefinder"
	reverseemaillookup "github.com/maximiseai/enrich-go-sdk/reverseemaillookup"
	teams "github.com/maximiseai/enrich-go-sdk/teams"
	wallets "github.com/maximiseai/enrich-go-sdk/wallets"
)

type Client struct {
	CompanyFollowers   *companyfollowers.Client
	EmailValidation    *emailvalidation.Client
	EmailFinder        *emailfinder.Client
	PhoneFinder        *phonefinder.Client
	ReverseEmailLookup *reverseemaillookup.Client
	Wallets            *wallets.Client
	Teams              *teams.Client
	LeadFinder         *leadfinder.Client
	PeopleSearch       *peoplesearch.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		CompanyFollowers:   companyfollowers.NewClient(options),
		EmailValidation:    emailvalidation.NewClient(options),
		EmailFinder:        emailfinder.NewClient(options),
		PhoneFinder:        phonefinder.NewClient(options),
		ReverseEmailLookup: reverseemaillookup.NewClient(options),
		Wallets:            wallets.NewClient(options),
		Teams:              teams.NewClient(options),
		LeadFinder:         leadfinder.NewClient(options),
		PeopleSearch:       peoplesearch.NewClient(options),
		options:            options,
		baseURL:            options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
