// Code generated by Fern. DO NOT EDIT.

package lead_finder_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	sdk "github.com/maximiseai/enrich-go-sdk"
	client "github.com/maximiseai/enrich-go-sdk/client"
	option "github.com/maximiseai/enrich-go-sdk/option"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestLeadFinderSearchLeadsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.LeadSearchRequest{
		Filters: &sdk.LeadFinderSearchFilters{},
	}
	_, invocationErr := client.LeadFinder.SearchLeads(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLeadFinderSearchLeadsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLeadFinderSearchLeadsWithWireMock", "POST", "/lead-finder/search", nil, 1)
}

func TestLeadFinderCountLeadsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.LeadCountRequest{
		Filters: &sdk.LeadFinderSearchFilters{},
	}
	_, invocationErr := client.LeadFinder.CountLeads(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLeadFinderCountLeadsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLeadFinderCountLeadsWithWireMock", "POST", "/lead-finder/count", nil, 1)
}

func TestLeadFinderExportLeadsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.LeadExportRequest{
		Filters: &sdk.LeadFinderSearchFilters{},
	}
	_, invocationErr := client.LeadFinder.ExportLeads(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLeadFinderExportLeadsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLeadFinderExportLeadsWithWireMock", "POST", "/lead-finder/export", nil, 1)
}

func TestLeadFinderRevealLeadsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.LeadRevealRequest{
		Leads: []*sdk.LeadRevealRequestLeadsItem{
			&sdk.LeadRevealRequestLeadsItem{
				ID: "enc_abc123def456",
			},
		},
		Fields: []sdk.LeadRevealRequestFieldsItem{
			sdk.LeadRevealRequestFieldsItemEmail,
		},
	}
	_, invocationErr := client.LeadFinder.RevealLeads(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLeadFinderRevealLeadsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLeadFinderRevealLeadsWithWireMock", "POST", "/lead-finder/reveal", nil, 1)
}

func TestLeadFinderEnrichLeadsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.LeadEnrichRequest{
		Leads: []*sdk.LeadEnrichRequestLeadsItem{
			&sdk.LeadEnrichRequestLeadsItem{
				ID: "id",
			},
		},
		Fields: []sdk.LeadEnrichRequestFieldsItem{
			sdk.LeadEnrichRequestFieldsItemEmail,
		},
	}
	_, invocationErr := client.LeadFinder.EnrichLeads(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLeadFinderEnrichLeadsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLeadFinderEnrichLeadsWithWireMock", "POST", "/lead-finder/enrich", nil, 1)
}

func TestLeadFinderUnlockNamesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.UnlockNamesRequest{
		Leads: []*sdk.UnlockNamesRequestLeadsItem{
			&sdk.UnlockNamesRequestLeadsItem{
				ID: "id",
			},
		},
	}
	_, invocationErr := client.LeadFinder.UnlockNames(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLeadFinderUnlockNamesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLeadFinderUnlockNamesWithWireMock", "POST", "/lead-finder/unlock-names", nil, 1)
}

func TestLeadFinderListSavedSearchesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.LeadFinder.ListSavedSearches(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLeadFinderListSavedSearchesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLeadFinderListSavedSearchesWithWireMock", "GET", "/lead-finder/saved", nil, 1)
}

func TestLeadFinderCreateSavedSearchWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SavedSearchCreateRequest{
		Name:    "name",
		Filters: &sdk.LeadFinderSearchFilters{},
	}
	_, invocationErr := client.LeadFinder.CreateSavedSearch(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLeadFinderCreateSavedSearchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLeadFinderCreateSavedSearchWithWireMock", "POST", "/lead-finder/saved", nil, 1)
}

func TestLeadFinderDeleteSavedSearchWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.DeleteSavedSearchRequest{
		ID: "665e0b2f4a6d8c001abc1234",
	}
	_, invocationErr := client.LeadFinder.DeleteSavedSearch(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLeadFinderDeleteSavedSearchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLeadFinderDeleteSavedSearchWithWireMock", "DELETE", "/lead-finder/saved/665e0b2f4a6d8c001abc1234", nil, 1)
}

func TestLeadFinderGetFilterOptionsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.LeadFinder.GetFilterOptions(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLeadFinderGetFilterOptionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLeadFinderGetFilterOptionsWithWireMock", "GET", "/lead-finder/filter-options", nil, 1)
}

func TestLeadFinderSuggestCompanyNamesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SuggestCompanyNamesRequest{
		Q: "Stri",
	}
	_, invocationErr := client.LeadFinder.SuggestCompanyNames(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLeadFinderSuggestCompanyNamesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLeadFinderSuggestCompanyNamesWithWireMock", "GET", "/lead-finder/suggest", map[string]string{"q": "Stri"}, 1)
}
