// Code generated by Fern. DO NOT EDIT.

package phonefinder

import (
	context "context"
	sdk "github.com/maximiseai/enrich-go-sdk"
	core "github.com/maximiseai/enrich-go-sdk/core"
	internal "github.com/maximiseai/enrich-go-sdk/internal"
	option "github.com/maximiseai/enrich-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Find phone numbers associated with a person's email address or social
// profile URL. You must provide at least one of the two.
//
// **Cost:** 500 credits. You are **not** charged if no phone numbers are found.
func (c *Client) PhoneLookup(
	ctx context.Context,
	request *sdk.PhoneLookupRequest,
	opts ...option.RequestOption,
) (*sdk.PhoneLookupResponse, error) {
	response, err := c.WithRawResponse.PhoneLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Submit up to **500 000 items** (email addresses and/or profile URLs) for
// bulk phone lookup. Emails are deduplicated case-insensitively; profile
// URLs are deduplicated as-is.
//
// **Cost:** 10 credits per unique item, reserved upfront. At settlement,
// only items where phones were actually found are charged — the rest are
// refunded.
//
// ### Webhook callbacks
//
// If you include a `webhookUrl`, your server will receive:
//
//  1. **A per-result callback** for every item as it is processed. See
//     [phoneResult](#tag/Webhooks/operation/webhookPhoneResult) for the payload.
//
//  2. **A completion callback** when every item has been processed. See
//     [phoneCompletion](#tag/Webhooks/operation/webhookPhoneCompletion) for the payload.
func (c *Client) CreatePhoneBulkJob(
	ctx context.Context,
	request *sdk.PhoneBatchRequest,
	opts ...option.RequestOption,
) (*sdk.PhoneBulkJobSubmitResponse, error) {
	response, err := c.WithRawResponse.CreatePhoneBulkJob(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Poll this endpoint to track the job. The `progress` field is a percentage
// from 0 to 100.
//
// **Cost:** Free.
func (c *Client) GetPhoneBulkJobStatus(
	ctx context.Context,
	request *sdk.GetPhoneBulkJobStatusRequest,
	opts ...option.RequestOption,
) (*sdk.PhoneBulkJobStatusResponse, error) {
	response, err := c.WithRawResponse.GetPhoneBulkJobStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve paginated results. Each item shows the phones found (or an error
// message if the lookup failed).
//
// **Credit settlement:** Only items where at least one phone number was found
// are charged. Everything else is refunded.
func (c *Client) GetPhoneBulkJobResults(
	ctx context.Context,
	request *sdk.GetPhoneBulkJobResultsRequest,
	opts ...option.RequestOption,
) (*sdk.PhoneBulkJobResultsResponse, error) {
	response, err := c.WithRawResponse.GetPhoneBulkJobResults(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
