// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "github.com/maximiseai/enrich-go-sdk/internal"
)

var (
	batchEmailFinderRequestFieldLeads      = big.NewInt(1 << 0)
	batchEmailFinderRequestFieldWebhookURL = big.NewInt(1 << 1)
)

type BatchEmailFinderRequest struct {
	// The list of people to search for (up to 500 000)
	Leads []*Lead `json:"leads" url:"-"`
	// A URL on your server where we should send webhook callbacks.
	// You'll receive one POST per lead, plus one final completion POST.
	WebhookURL *string `json:"webhookUrl,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *BatchEmailFinderRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetLeads sets the Leads field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BatchEmailFinderRequest) SetLeads(leads []*Lead) {
	b.Leads = leads
	b.require(batchEmailFinderRequestFieldLeads)
}

// SetWebhookURL sets the WebhookURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BatchEmailFinderRequest) SetWebhookURL(webhookURL *string) {
	b.WebhookURL = webhookURL
	b.require(batchEmailFinderRequestFieldWebhookURL)
}

func (b *BatchEmailFinderRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler BatchEmailFinderRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*b = BatchEmailFinderRequest(body)
	return nil
}

func (b *BatchEmailFinderRequest) MarshalJSON() ([]byte, error) {
	type embed BatchEmailFinderRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	emailFinderRequestFieldFirstName = big.NewInt(1 << 0)
	emailFinderRequestFieldLastName  = big.NewInt(1 << 1)
	emailFinderRequestFieldDomain    = big.NewInt(1 << 2)
)

type EmailFinderRequest struct {
	// The person's first name
	FirstName string `json:"firstName" url:"-"`
	// The person's last name
	LastName string `json:"lastName" url:"-"`
	// The company domain to search (e.g. `figma.com`)
	Domain string `json:"domain" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (e *EmailFinderRequest) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetFirstName sets the FirstName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderRequest) SetFirstName(firstName string) {
	e.FirstName = firstName
	e.require(emailFinderRequestFieldFirstName)
}

// SetLastName sets the LastName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderRequest) SetLastName(lastName string) {
	e.LastName = lastName
	e.require(emailFinderRequestFieldLastName)
}

// SetDomain sets the Domain field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderRequest) SetDomain(domain string) {
	e.Domain = domain
	e.require(emailFinderRequestFieldDomain)
}

func (e *EmailFinderRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler EmailFinderRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*e = EmailFinderRequest(body)
	return nil
}

func (e *EmailFinderRequest) MarshalJSON() ([]byte, error) {
	type embed EmailFinderRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getEmailFinderBatchResultsRequestFieldBatchID = big.NewInt(1 << 0)
	getEmailFinderBatchResultsRequestFieldPage    = big.NewInt(1 << 1)
	getEmailFinderBatchResultsRequestFieldLimit   = big.NewInt(1 << 2)
)

type GetEmailFinderBatchResultsRequest struct {
	// The batch identifier returned when you submitted the job
	BatchID string `json:"-" url:"-"`
	// Page number (default: 1)
	Page *int `json:"-" url:"page,omitempty"`
	// Results per page (default: 100, max: 1 000)
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetEmailFinderBatchResultsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetBatchID sets the BatchID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEmailFinderBatchResultsRequest) SetBatchID(batchID string) {
	g.BatchID = batchID
	g.require(getEmailFinderBatchResultsRequestFieldBatchID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEmailFinderBatchResultsRequest) SetPage(page *int) {
	g.Page = page
	g.require(getEmailFinderBatchResultsRequestFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEmailFinderBatchResultsRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getEmailFinderBatchResultsRequestFieldLimit)
}

var (
	getEmailFinderBatchStatusRequestFieldBatchID = big.NewInt(1 << 0)
)

type GetEmailFinderBatchStatusRequest struct {
	// The batch identifier returned when you submitted the job
	BatchID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetEmailFinderBatchStatusRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetBatchID sets the BatchID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEmailFinderBatchStatusRequest) SetBatchID(batchID string) {
	g.BatchID = batchID
	g.require(getEmailFinderBatchStatusRequestFieldBatchID)
}

var (
	emailFinderBatchResultsResponseFieldData = big.NewInt(1 << 0)
	emailFinderBatchResultsResponseFieldMeta = big.NewInt(1 << 1)
)

type EmailFinderBatchResultsResponse struct {
	Data *EmailFinderBatchResultsResponseData `json:"data" url:"data"`
	Meta *BatchResultsMeta                    `json:"meta,omitempty" url:"meta,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	success        bool

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EmailFinderBatchResultsResponse) GetData() *EmailFinderBatchResultsResponseData {
	if e == nil {
		return nil
	}
	return e.Data
}

func (e *EmailFinderBatchResultsResponse) GetMeta() *BatchResultsMeta {
	if e == nil {
		return nil
	}
	return e.Meta
}

func (e *EmailFinderBatchResultsResponse) Success() bool {
	return e.success
}

func (e *EmailFinderBatchResultsResponse) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EmailFinderBatchResultsResponse) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderBatchResultsResponse) SetData(data *EmailFinderBatchResultsResponseData) {
	e.Data = data
	e.require(emailFinderBatchResultsResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderBatchResultsResponse) SetMeta(meta *BatchResultsMeta) {
	e.Meta = meta
	e.require(emailFinderBatchResultsResponseFieldMeta)
}

func (e *EmailFinderBatchResultsResponse) UnmarshalJSON(data []byte) error {
	type embed EmailFinderBatchResultsResponse
	var unmarshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed: embed(*e),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*e = EmailFinderBatchResultsResponse(unmarshaler.embed)
	if unmarshaler.Success != true {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", e, true, unmarshaler.Success)
	}
	e.success = unmarshaler.Success
	extraProperties, err := internal.ExtractExtraProperties(data, *e, "success")
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EmailFinderBatchResultsResponse) MarshalJSON() ([]byte, error) {
	type embed EmailFinderBatchResultsResponse
	var marshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed:   embed(*e),
		Success: true,
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EmailFinderBatchResultsResponse) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	emailFinderBatchResultsResponseDataFieldBatchID        = big.NewInt(1 << 0)
	emailFinderBatchResultsResponseDataFieldStatus         = big.NewInt(1 << 1)
	emailFinderBatchResultsResponseDataFieldTotalItems     = big.NewInt(1 << 2)
	emailFinderBatchResultsResponseDataFieldProcessedCount = big.NewInt(1 << 3)
	emailFinderBatchResultsResponseDataFieldResults        = big.NewInt(1 << 4)
)

type EmailFinderBatchResultsResponseData struct {
	// The batch identifier
	BatchID string `json:"batchId" url:"batchId"`
	// Final batch status
	Status string `json:"status" url:"status"`
	// Total leads in the batch
	TotalItems *int `json:"totalItems,omitempty" url:"totalItems,omitempty"`
	// Leads that were processed
	ProcessedCount *int `json:"processedCount,omitempty" url:"processedCount,omitempty"`
	// The finder results
	Results []*EmailFinderResult `json:"results,omitempty" url:"results,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EmailFinderBatchResultsResponseData) GetBatchID() string {
	if e == nil {
		return ""
	}
	return e.BatchID
}

func (e *EmailFinderBatchResultsResponseData) GetStatus() string {
	if e == nil {
		return ""
	}
	return e.Status
}

func (e *EmailFinderBatchResultsResponseData) GetTotalItems() *int {
	if e == nil {
		return nil
	}
	return e.TotalItems
}

func (e *EmailFinderBatchResultsResponseData) GetProcessedCount() *int {
	if e == nil {
		return nil
	}
	return e.ProcessedCount
}

func (e *EmailFinderBatchResultsResponseData) GetResults() []*EmailFinderResult {
	if e == nil {
		return nil
	}
	return e.Results
}

func (e *EmailFinderBatchResultsResponseData) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EmailFinderBatchResultsResponseData) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetBatchID sets the BatchID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderBatchResultsResponseData) SetBatchID(batchID string) {
	e.BatchID = batchID
	e.require(emailFinderBatchResultsResponseDataFieldBatchID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderBatchResultsResponseData) SetStatus(status string) {
	e.Status = status
	e.require(emailFinderBatchResultsResponseDataFieldStatus)
}

// SetTotalItems sets the TotalItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderBatchResultsResponseData) SetTotalItems(totalItems *int) {
	e.TotalItems = totalItems
	e.require(emailFinderBatchResultsResponseDataFieldTotalItems)
}

// SetProcessedCount sets the ProcessedCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderBatchResultsResponseData) SetProcessedCount(processedCount *int) {
	e.ProcessedCount = processedCount
	e.require(emailFinderBatchResultsResponseDataFieldProcessedCount)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderBatchResultsResponseData) SetResults(results []*EmailFinderResult) {
	e.Results = results
	e.require(emailFinderBatchResultsResponseDataFieldResults)
}

func (e *EmailFinderBatchResultsResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler EmailFinderBatchResultsResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EmailFinderBatchResultsResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EmailFinderBatchResultsResponseData) MarshalJSON() ([]byte, error) {
	type embed EmailFinderBatchResultsResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EmailFinderBatchResultsResponseData) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	emailFinderResponseFieldData = big.NewInt(1 << 0)
	emailFinderResponseFieldMeta = big.NewInt(1 << 1)
)

type EmailFinderResponse struct {
	Data *EmailFinderResult `json:"data" url:"data"`
	Meta *EnrichmentMeta    `json:"meta,omitempty" url:"meta,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	success        bool

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EmailFinderResponse) GetData() *EmailFinderResult {
	if e == nil {
		return nil
	}
	return e.Data
}

func (e *EmailFinderResponse) GetMeta() *EnrichmentMeta {
	if e == nil {
		return nil
	}
	return e.Meta
}

func (e *EmailFinderResponse) Success() bool {
	return e.success
}

func (e *EmailFinderResponse) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EmailFinderResponse) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderResponse) SetData(data *EmailFinderResult) {
	e.Data = data
	e.require(emailFinderResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderResponse) SetMeta(meta *EnrichmentMeta) {
	e.Meta = meta
	e.require(emailFinderResponseFieldMeta)
}

func (e *EmailFinderResponse) UnmarshalJSON(data []byte) error {
	type embed EmailFinderResponse
	var unmarshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed: embed(*e),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*e = EmailFinderResponse(unmarshaler.embed)
	if unmarshaler.Success != true {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", e, true, unmarshaler.Success)
	}
	e.success = unmarshaler.Success
	extraProperties, err := internal.ExtractExtraProperties(data, *e, "success")
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EmailFinderResponse) MarshalJSON() ([]byte, error) {
	type embed EmailFinderResponse
	var marshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed:   embed(*e),
		Success: true,
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EmailFinderResponse) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// The result of searching for one person's email
var (
	emailFinderResultFieldFirstName  = big.NewInt(1 << 0)
	emailFinderResultFieldLastName   = big.NewInt(1 << 1)
	emailFinderResultFieldDomain     = big.NewInt(1 << 2)
	emailFinderResultFieldFound      = big.NewInt(1 << 3)
	emailFinderResultFieldEmail      = big.NewInt(1 << 4)
	emailFinderResultFieldConfidence = big.NewInt(1 << 5)
	emailFinderResultFieldIsCatchAll = big.NewInt(1 << 6)
	emailFinderResultFieldProvider   = big.NewInt(1 << 7)
	emailFinderResultFieldMessage    = big.NewInt(1 << 8)
)

type EmailFinderResult struct {
	// The first name you searched for
	FirstName string `json:"firstName" url:"firstName"`
	// The last name you searched for
	LastName string `json:"lastName" url:"lastName"`
	// The domain you searched
	Domain string `json:"domain" url:"domain"`
	// Whether we found an email for this person
	Found bool `json:"found" url:"found"`
	// The email address we found (only present when `found` is `true`)
	Email *string `json:"email,omitempty" url:"email,omitempty"`
	// How confident we are that this is the right address
	Confidence *EmailFinderResultConfidence `json:"confidence,omitempty" url:"confidence,omitempty"`
	// Whether the domain is a catch-all (accepts any address)
	IsCatchAll *bool `json:"isCatchAll,omitempty" url:"isCatchAll,omitempty"`
	// The email provider detected for this domain (e.g. GOOGLE, MICROSOFT, ZOHO, FASTMAIL, PROTONMAIL)
	Provider *string `json:"provider,omitempty" url:"provider,omitempty"`
	// A human-readable explanation
	Message string `json:"message" url:"message"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EmailFinderResult) GetFirstName() string {
	if e == nil {
		return ""
	}
	return e.FirstName
}

func (e *EmailFinderResult) GetLastName() string {
	if e == nil {
		return ""
	}
	return e.LastName
}

func (e *EmailFinderResult) GetDomain() string {
	if e == nil {
		return ""
	}
	return e.Domain
}

func (e *EmailFinderResult) GetFound() bool {
	if e == nil {
		return false
	}
	return e.Found
}

func (e *EmailFinderResult) GetEmail() *string {
	if e == nil {
		return nil
	}
	return e.Email
}

func (e *EmailFinderResult) GetConfidence() *EmailFinderResultConfidence {
	if e == nil {
		return nil
	}
	return e.Confidence
}

func (e *EmailFinderResult) GetIsCatchAll() *bool {
	if e == nil {
		return nil
	}
	return e.IsCatchAll
}

func (e *EmailFinderResult) GetProvider() *string {
	if e == nil {
		return nil
	}
	return e.Provider
}

func (e *EmailFinderResult) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *EmailFinderResult) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EmailFinderResult) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetFirstName sets the FirstName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderResult) SetFirstName(firstName string) {
	e.FirstName = firstName
	e.require(emailFinderResultFieldFirstName)
}

// SetLastName sets the LastName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderResult) SetLastName(lastName string) {
	e.LastName = lastName
	e.require(emailFinderResultFieldLastName)
}

// SetDomain sets the Domain field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderResult) SetDomain(domain string) {
	e.Domain = domain
	e.require(emailFinderResultFieldDomain)
}

// SetFound sets the Found field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderResult) SetFound(found bool) {
	e.Found = found
	e.require(emailFinderResultFieldFound)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderResult) SetEmail(email *string) {
	e.Email = email
	e.require(emailFinderResultFieldEmail)
}

// SetConfidence sets the Confidence field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderResult) SetConfidence(confidence *EmailFinderResultConfidence) {
	e.Confidence = confidence
	e.require(emailFinderResultFieldConfidence)
}

// SetIsCatchAll sets the IsCatchAll field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderResult) SetIsCatchAll(isCatchAll *bool) {
	e.IsCatchAll = isCatchAll
	e.require(emailFinderResultFieldIsCatchAll)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderResult) SetProvider(provider *string) {
	e.Provider = provider
	e.require(emailFinderResultFieldProvider)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmailFinderResult) SetMessage(message string) {
	e.Message = message
	e.require(emailFinderResultFieldMessage)
}

func (e *EmailFinderResult) UnmarshalJSON(data []byte) error {
	type unmarshaler EmailFinderResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EmailFinderResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EmailFinderResult) MarshalJSON() ([]byte, error) {
	type embed EmailFinderResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EmailFinderResult) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// How confident we are that this is the right address
type EmailFinderResultConfidence string

const (
	EmailFinderResultConfidenceHigh   EmailFinderResultConfidence = "high"
	EmailFinderResultConfidenceMedium EmailFinderResultConfidence = "medium"
	EmailFinderResultConfidenceLow    EmailFinderResultConfidence = "low"
)

func NewEmailFinderResultConfidenceFromString(s string) (EmailFinderResultConfidence, error) {
	switch s {
	case "high":
		return EmailFinderResultConfidenceHigh, nil
	case "medium":
		return EmailFinderResultConfidenceMedium, nil
	case "low":
		return EmailFinderResultConfidenceLow, nil
	}
	var t EmailFinderResultConfidence
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e EmailFinderResultConfidence) Ptr() *EmailFinderResultConfidence {
	return &e
}

// A single person to find an email for
var (
	leadFieldFirstName = big.NewInt(1 << 0)
	leadFieldLastName  = big.NewInt(1 << 1)
	leadFieldDomain    = big.NewInt(1 << 2)
)

type Lead struct {
	// First name
	FirstName string `json:"firstName" url:"firstName"`
	// Last name
	LastName string `json:"lastName" url:"lastName"`
	// Company domain
	Domain string `json:"domain" url:"domain"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *Lead) GetFirstName() string {
	if l == nil {
		return ""
	}
	return l.FirstName
}

func (l *Lead) GetLastName() string {
	if l == nil {
		return ""
	}
	return l.LastName
}

func (l *Lead) GetDomain() string {
	if l == nil {
		return ""
	}
	return l.Domain
}

func (l *Lead) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *Lead) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetFirstName sets the FirstName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *Lead) SetFirstName(firstName string) {
	l.FirstName = firstName
	l.require(leadFieldFirstName)
}

// SetLastName sets the LastName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *Lead) SetLastName(lastName string) {
	l.LastName = lastName
	l.require(leadFieldLastName)
}

// SetDomain sets the Domain field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *Lead) SetDomain(domain string) {
	l.Domain = domain
	l.require(leadFieldDomain)
}

func (l *Lead) UnmarshalJSON(data []byte) error {
	type unmarshaler Lead
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = Lead(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *Lead) MarshalJSON() ([]byte, error) {
	type embed Lead
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *Lead) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
