// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersBatchEmailValidationRequest(t *testing.T) {
	t.Run("SetEmails", func(t *testing.T) {
		obj := &BatchEmailValidationRequest{}
		var fernTestValueEmails []string
		obj.SetEmails(fernTestValueEmails)
		assert.Equal(t, fernTestValueEmails, obj.Emails)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWebhookURL", func(t *testing.T) {
		obj := &BatchEmailValidationRequest{}
		var fernTestValueWebhookURL *string
		obj.SetWebhookURL(fernTestValueWebhookURL)
		assert.Equal(t, fernTestValueWebhookURL, obj.WebhookURL)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitBatchEmailValidationRequest(t *testing.T) {
	t.Run("SetEmails_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BatchEmailValidationRequest{}
		var fernTestValueEmails []string

		// Act
		obj.SetEmails(fernTestValueEmails)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWebhookURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BatchEmailValidationRequest{}
		var fernTestValueWebhookURL *string

		// Act
		obj.SetWebhookURL(fernTestValueWebhookURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetEmailValidationBatchResultsRequest(t *testing.T) {
	t.Run("SetBatchID", func(t *testing.T) {
		obj := &GetEmailValidationBatchResultsRequest{}
		var fernTestValueBatchID string
		obj.SetBatchID(fernTestValueBatchID)
		assert.Equal(t, fernTestValueBatchID, obj.BatchID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &GetEmailValidationBatchResultsRequest{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLimit", func(t *testing.T) {
		obj := &GetEmailValidationBatchResultsRequest{}
		var fernTestValueLimit *int
		obj.SetLimit(fernTestValueLimit)
		assert.Equal(t, fernTestValueLimit, obj.Limit)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetEmailValidationBatchResultsRequest(t *testing.T) {
	t.Run("SetBatchID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetEmailValidationBatchResultsRequest{}
		var fernTestValueBatchID string

		// Act
		obj.SetBatchID(fernTestValueBatchID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetEmailValidationBatchResultsRequest{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetEmailValidationBatchResultsRequest{}
		var fernTestValueLimit *int

		// Act
		obj.SetLimit(fernTestValueLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetEmailValidationBatchStatusRequest(t *testing.T) {
	t.Run("SetBatchID", func(t *testing.T) {
		obj := &GetEmailValidationBatchStatusRequest{}
		var fernTestValueBatchID string
		obj.SetBatchID(fernTestValueBatchID)
		assert.Equal(t, fernTestValueBatchID, obj.BatchID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetEmailValidationBatchStatusRequest(t *testing.T) {
	t.Run("SetBatchID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetEmailValidationBatchStatusRequest{}
		var fernTestValueBatchID string

		// Act
		obj.SetBatchID(fernTestValueBatchID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersEmailValidationBatchResultsResponse(t *testing.T) {
	t.Run("SetData", func(t *testing.T) {
		obj := &EmailValidationBatchResultsResponse{}
		var fernTestValueData *EmailValidationBatchResultsResponseData
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMeta", func(t *testing.T) {
		obj := &EmailValidationBatchResultsResponse{}
		var fernTestValueMeta *BatchResultsMeta
		obj.SetMeta(fernTestValueMeta)
		assert.Equal(t, fernTestValueMeta, obj.Meta)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersEmailValidationBatchResultsResponse(t *testing.T) {
	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponse{}
		var expected *EmailValidationBatchResultsResponseData
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponse{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationBatchResultsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

	t.Run("GetMeta", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponse{}
		var expected *BatchResultsMeta
		obj.Meta = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMeta(), "getter should return the property value")
	})

	t.Run("GetMeta_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponse{}
		obj.Meta = nil

		// Act & Assert
		assert.Nil(t, obj.GetMeta(), "getter should return nil when property is nil")
	})

	t.Run("GetMeta_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationBatchResultsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMeta() // Should return zero value
	})

}

func TestSettersMarkExplicitEmailValidationBatchResultsResponse(t *testing.T) {
	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponse{}
		var fernTestValueData *EmailValidationBatchResultsResponseData

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMeta_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponse{}
		var fernTestValueMeta *BatchResultsMeta

		// Act
		obj.SetMeta(fernTestValueMeta)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersEmailValidationBatchResultsResponseData(t *testing.T) {
	t.Run("SetBatchID", func(t *testing.T) {
		obj := &EmailValidationBatchResultsResponseData{}
		var fernTestValueBatchID string
		obj.SetBatchID(fernTestValueBatchID)
		assert.Equal(t, fernTestValueBatchID, obj.BatchID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &EmailValidationBatchResultsResponseData{}
		var fernTestValueStatus string
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTotalItems", func(t *testing.T) {
		obj := &EmailValidationBatchResultsResponseData{}
		var fernTestValueTotalItems *int
		obj.SetTotalItems(fernTestValueTotalItems)
		assert.Equal(t, fernTestValueTotalItems, obj.TotalItems)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProcessedCount", func(t *testing.T) {
		obj := &EmailValidationBatchResultsResponseData{}
		var fernTestValueProcessedCount *int
		obj.SetProcessedCount(fernTestValueProcessedCount)
		assert.Equal(t, fernTestValueProcessedCount, obj.ProcessedCount)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResults", func(t *testing.T) {
		obj := &EmailValidationBatchResultsResponseData{}
		var fernTestValueResults []*EmailValidationResult
		obj.SetResults(fernTestValueResults)
		assert.Equal(t, fernTestValueResults, obj.Results)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersEmailValidationBatchResultsResponseData(t *testing.T) {
	t.Run("GetBatchID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}
		var expected string
		obj.BatchID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBatchID(), "getter should return the property value")
	})

	t.Run("GetBatchID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationBatchResultsResponseData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBatchID() // Should return zero value
	})

	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}
		var expected string
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationBatchResultsResponseData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

	t.Run("GetTotalItems", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}
		var expected *int
		obj.TotalItems = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTotalItems(), "getter should return the property value")
	})

	t.Run("GetTotalItems_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}
		obj.TotalItems = nil

		// Act & Assert
		assert.Nil(t, obj.GetTotalItems(), "getter should return nil when property is nil")
	})

	t.Run("GetTotalItems_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationBatchResultsResponseData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTotalItems() // Should return zero value
	})

	t.Run("GetProcessedCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}
		var expected *int
		obj.ProcessedCount = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProcessedCount(), "getter should return the property value")
	})

	t.Run("GetProcessedCount_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}
		obj.ProcessedCount = nil

		// Act & Assert
		assert.Nil(t, obj.GetProcessedCount(), "getter should return nil when property is nil")
	})

	t.Run("GetProcessedCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationBatchResultsResponseData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProcessedCount() // Should return zero value
	})

	t.Run("GetResults", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}
		var expected []*EmailValidationResult
		obj.Results = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResults(), "getter should return the property value")
	})

	t.Run("GetResults_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}
		obj.Results = nil

		// Act & Assert
		assert.Nil(t, obj.GetResults(), "getter should return nil when property is nil")
	})

	t.Run("GetResults_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationBatchResultsResponseData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResults() // Should return zero value
	})

}

func TestSettersMarkExplicitEmailValidationBatchResultsResponseData(t *testing.T) {
	t.Run("SetBatchID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}
		var fernTestValueBatchID string

		// Act
		obj.SetBatchID(fernTestValueBatchID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}
		var fernTestValueStatus string

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTotalItems_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}
		var fernTestValueTotalItems *int

		// Act
		obj.SetTotalItems(fernTestValueTotalItems)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProcessedCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}
		var fernTestValueProcessedCount *int

		// Act
		obj.SetProcessedCount(fernTestValueProcessedCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResults_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}
		var fernTestValueResults []*EmailValidationResult

		// Act
		obj.SetResults(fernTestValueResults)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersEmailValidationResponse(t *testing.T) {
	t.Run("SetData", func(t *testing.T) {
		obj := &EmailValidationResponse{}
		var fernTestValueData *EmailValidationResult
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMeta", func(t *testing.T) {
		obj := &EmailValidationResponse{}
		var fernTestValueMeta *EnrichmentMeta
		obj.SetMeta(fernTestValueMeta)
		assert.Equal(t, fernTestValueMeta, obj.Meta)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersEmailValidationResponse(t *testing.T) {
	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResponse{}
		var expected *EmailValidationResult
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResponse{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

	t.Run("GetMeta", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResponse{}
		var expected *EnrichmentMeta
		obj.Meta = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMeta(), "getter should return the property value")
	})

	t.Run("GetMeta_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResponse{}
		obj.Meta = nil

		// Act & Assert
		assert.Nil(t, obj.GetMeta(), "getter should return nil when property is nil")
	})

	t.Run("GetMeta_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMeta() // Should return zero value
	})

}

func TestSettersMarkExplicitEmailValidationResponse(t *testing.T) {
	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResponse{}
		var fernTestValueData *EmailValidationResult

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMeta_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResponse{}
		var fernTestValueMeta *EnrichmentMeta

		// Act
		obj.SetMeta(fernTestValueMeta)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersEmailValidationResult(t *testing.T) {
	t.Run("SetEmail", func(t *testing.T) {
		obj := &EmailValidationResult{}
		var fernTestValueEmail string
		obj.SetEmail(fernTestValueEmail)
		assert.Equal(t, fernTestValueEmail, obj.Email)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResult", func(t *testing.T) {
		obj := &EmailValidationResult{}
		var fernTestValueResult EmailValidationResultResult
		obj.SetResult(fernTestValueResult)
		assert.Equal(t, fernTestValueResult, obj.Result)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMessage", func(t *testing.T) {
		obj := &EmailValidationResult{}
		var fernTestValueMessage string
		obj.SetMessage(fernTestValueMessage)
		assert.Equal(t, fernTestValueMessage, obj.Message)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIsCatchAll", func(t *testing.T) {
		obj := &EmailValidationResult{}
		var fernTestValueIsCatchAll bool
		obj.SetIsCatchAll(fernTestValueIsCatchAll)
		assert.Equal(t, fernTestValueIsCatchAll, obj.IsCatchAll)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIsFederated", func(t *testing.T) {
		obj := &EmailValidationResult{}
		var fernTestValueIsFederated *bool
		obj.SetIsFederated(fernTestValueIsFederated)
		assert.Equal(t, fernTestValueIsFederated, obj.IsFederated)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHasSeg", func(t *testing.T) {
		obj := &EmailValidationResult{}
		var fernTestValueHasSeg *bool
		obj.SetHasSeg(fernTestValueHasSeg)
		assert.Equal(t, fernTestValueHasSeg, obj.HasSeg)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSegProvider", func(t *testing.T) {
		obj := &EmailValidationResult{}
		var fernTestValueSegProvider *string
		obj.SetSegProvider(fernTestValueSegProvider)
		assert.Equal(t, fernTestValueSegProvider, obj.SegProvider)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProvider", func(t *testing.T) {
		obj := &EmailValidationResult{}
		var fernTestValueProvider *EmailValidationResultProvider
		obj.SetProvider(fernTestValueProvider)
		assert.Equal(t, fernTestValueProvider, obj.Provider)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetConfidence", func(t *testing.T) {
		obj := &EmailValidationResult{}
		var fernTestValueConfidence EmailValidationResultConfidence
		obj.SetConfidence(fernTestValueConfidence)
		assert.Equal(t, fernTestValueConfidence, obj.Confidence)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersEmailValidationResult(t *testing.T) {
	t.Run("GetEmail", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var expected string
		obj.Email = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEmail(), "getter should return the property value")
	})

	t.Run("GetEmail_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEmail() // Should return zero value
	})

	t.Run("GetResult", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var expected EmailValidationResultResult
		obj.Result = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResult(), "getter should return the property value")
	})

	t.Run("GetResult_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResult() // Should return zero value
	})

	t.Run("GetMessage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var expected string
		obj.Message = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMessage(), "getter should return the property value")
	})

	t.Run("GetMessage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMessage() // Should return zero value
	})

	t.Run("GetIsCatchAll", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var expected bool
		obj.IsCatchAll = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsCatchAll(), "getter should return the property value")
	})

	t.Run("GetIsCatchAll_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsCatchAll() // Should return zero value
	})

	t.Run("GetIsFederated", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var expected *bool
		obj.IsFederated = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsFederated(), "getter should return the property value")
	})

	t.Run("GetIsFederated_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		obj.IsFederated = nil

		// Act & Assert
		assert.Nil(t, obj.GetIsFederated(), "getter should return nil when property is nil")
	})

	t.Run("GetIsFederated_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsFederated() // Should return zero value
	})

	t.Run("GetHasSeg", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var expected *bool
		obj.HasSeg = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHasSeg(), "getter should return the property value")
	})

	t.Run("GetHasSeg_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		obj.HasSeg = nil

		// Act & Assert
		assert.Nil(t, obj.GetHasSeg(), "getter should return nil when property is nil")
	})

	t.Run("GetHasSeg_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHasSeg() // Should return zero value
	})

	t.Run("GetSegProvider", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var expected *string
		obj.SegProvider = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSegProvider(), "getter should return the property value")
	})

	t.Run("GetSegProvider_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		obj.SegProvider = nil

		// Act & Assert
		assert.Nil(t, obj.GetSegProvider(), "getter should return nil when property is nil")
	})

	t.Run("GetSegProvider_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSegProvider() // Should return zero value
	})

	t.Run("GetProvider", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var expected *EmailValidationResultProvider
		obj.Provider = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProvider(), "getter should return the property value")
	})

	t.Run("GetProvider_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		obj.Provider = nil

		// Act & Assert
		assert.Nil(t, obj.GetProvider(), "getter should return nil when property is nil")
	})

	t.Run("GetProvider_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProvider() // Should return zero value
	})

	t.Run("GetConfidence", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var expected EmailValidationResultConfidence
		obj.Confidence = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetConfidence(), "getter should return the property value")
	})

	t.Run("GetConfidence_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetConfidence() // Should return zero value
	})

}

func TestSettersMarkExplicitEmailValidationResult(t *testing.T) {
	t.Run("SetEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var fernTestValueEmail string

		// Act
		obj.SetEmail(fernTestValueEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResult_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var fernTestValueResult EmailValidationResultResult

		// Act
		obj.SetResult(fernTestValueResult)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMessage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var fernTestValueMessage string

		// Act
		obj.SetMessage(fernTestValueMessage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIsCatchAll_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var fernTestValueIsCatchAll bool

		// Act
		obj.SetIsCatchAll(fernTestValueIsCatchAll)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIsFederated_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var fernTestValueIsFederated *bool

		// Act
		obj.SetIsFederated(fernTestValueIsFederated)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHasSeg_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var fernTestValueHasSeg *bool

		// Act
		obj.SetHasSeg(fernTestValueHasSeg)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSegProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var fernTestValueSegProvider *string

		// Act
		obj.SetSegProvider(fernTestValueSegProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var fernTestValueProvider *EmailValidationResultProvider

		// Act
		obj.SetProvider(fernTestValueProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetConfidence_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}
		var fernTestValueConfidence EmailValidationResultConfidence

		// Act
		obj.SetConfidence(fernTestValueConfidence)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersEmailValidationRequest(t *testing.T) {
	t.Run("SetEmail", func(t *testing.T) {
		obj := &EmailValidationRequest{}
		var fernTestValueEmail string
		obj.SetEmail(fernTestValueEmail)
		assert.Equal(t, fernTestValueEmail, obj.Email)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitEmailValidationRequest(t *testing.T) {
	t.Run("SetEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationRequest{}
		var fernTestValueEmail string

		// Act
		obj.SetEmail(fernTestValueEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingEmailValidationBatchResultsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled EmailValidationBatchResultsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj EmailValidationBatchResultsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

}

func TestJSONMarshalingEmailValidationBatchResultsResponseData(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationBatchResultsResponseData{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled EmailValidationBatchResultsResponseData
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj EmailValidationBatchResultsResponseData
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj EmailValidationBatchResultsResponseData
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingEmailValidationResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled EmailValidationResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj EmailValidationResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

}

func TestJSONMarshalingEmailValidationResult(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EmailValidationResult{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled EmailValidationResult
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj EmailValidationResult
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj EmailValidationResult
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringEmailValidationBatchResultsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &EmailValidationBatchResultsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationBatchResultsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringEmailValidationBatchResultsResponseData(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &EmailValidationBatchResultsResponseData{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationBatchResultsResponseData
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringEmailValidationResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &EmailValidationResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringEmailValidationResult(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &EmailValidationResult{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResult
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumEmailValidationResultConfidence(t *testing.T) {
	t.Run("NewFromString_definitive", func(t *testing.T) {
		t.Parallel()
		val, err := NewEmailValidationResultConfidenceFromString("definitive")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EmailValidationResultConfidence("definitive"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_high", func(t *testing.T) {
		t.Parallel()
		val, err := NewEmailValidationResultConfidenceFromString("high")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EmailValidationResultConfidence("high"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_medium", func(t *testing.T) {
		t.Parallel()
		val, err := NewEmailValidationResultConfidenceFromString("medium")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EmailValidationResultConfidence("medium"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_low", func(t *testing.T) {
		t.Parallel()
		val, err := NewEmailValidationResultConfidenceFromString("low")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EmailValidationResultConfidence("low"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_temporary", func(t *testing.T) {
		t.Parallel()
		val, err := NewEmailValidationResultConfidenceFromString("temporary")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EmailValidationResultConfidence("temporary"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_none", func(t *testing.T) {
		t.Parallel()
		val, err := NewEmailValidationResultConfidenceFromString("none")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EmailValidationResultConfidence("none"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewEmailValidationResultConfidenceFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewEmailValidationResultConfidenceFromString("definitive")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumEmailValidationResultProvider(t *testing.T) {
	t.Run("NewFromString_GOOGLE", func(t *testing.T) {
		t.Parallel()
		val, err := NewEmailValidationResultProviderFromString("GOOGLE")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EmailValidationResultProvider("GOOGLE"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_MICROSOFT", func(t *testing.T) {
		t.Parallel()
		val, err := NewEmailValidationResultProviderFromString("MICROSOFT")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EmailValidationResultProvider("MICROSOFT"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_SMTP", func(t *testing.T) {
		t.Parallel()
		val, err := NewEmailValidationResultProviderFromString("SMTP")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EmailValidationResultProvider("SMTP"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewEmailValidationResultProviderFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewEmailValidationResultProviderFromString("GOOGLE")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumEmailValidationResultResult(t *testing.T) {
	t.Run("NewFromString_valid", func(t *testing.T) {
		t.Parallel()
		val, err := NewEmailValidationResultResultFromString("valid")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EmailValidationResultResult("valid"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_invalid", func(t *testing.T) {
		t.Parallel()
		val, err := NewEmailValidationResultResultFromString("invalid")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EmailValidationResultResult("invalid"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_risky", func(t *testing.T) {
		t.Parallel()
		val, err := NewEmailValidationResultResultFromString("risky")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EmailValidationResultResult("risky"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewEmailValidationResultResultFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewEmailValidationResultResultFromString("valid")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesEmailValidationBatchResultsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &EmailValidationBatchResultsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationBatchResultsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesEmailValidationBatchResultsResponseData(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &EmailValidationBatchResultsResponseData{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationBatchResultsResponseData
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesEmailValidationResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &EmailValidationResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesEmailValidationResult(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &EmailValidationResult{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EmailValidationResult
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
