// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "github.com/maximiseai/enrich-go-sdk/internal"
)

var (
	employeeFinderRequestFieldCompanyLinkedinURL = big.NewInt(1 << 0)
	employeeFinderRequestFieldCountry            = big.NewInt(1 << 1)
	employeeFinderRequestFieldContinent          = big.NewInt(1 << 2)
	employeeFinderRequestFieldSalesRegion        = big.NewInt(1 << 3)
	employeeFinderRequestFieldJobLevel           = big.NewInt(1 << 4)
	employeeFinderRequestFieldJobFunction        = big.NewInt(1 << 5)
	employeeFinderRequestFieldMaxResults         = big.NewInt(1 << 6)
	employeeFinderRequestFieldPage               = big.NewInt(1 << 7)
)

type EmployeeFinderRequest struct {
	// LinkedIn company profile URL (required). Must be a valid LinkedIn company URL.
	CompanyLinkedinURL string `json:"company_linkedin_url" url:"-"`
	// Country names to filter (e.g. "India", "United States", "Germany")
	Country []string `json:"country,omitempty" url:"-"`
	// Continent filter
	Continent []string `json:"continent,omitempty" url:"-"`
	// Sales region filter
	SalesRegion []string `json:"sales_region,omitempty" url:"-"`
	// Job level/seniority filter
	JobLevel []string `json:"job_level,omitempty" url:"-"`
	// Job function/department filter
	JobFunction []string `json:"job_function,omitempty" url:"-"`
	// Results per page (1-100, default 10)
	MaxResults *int `json:"max_results,omitempty" url:"-"`
	// Page number (starts at 1)
	Page *int `json:"page,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (e *EmployeeFinderRequest) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetCompanyLinkedinURL sets the CompanyLinkedinURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderRequest) SetCompanyLinkedinURL(companyLinkedinURL string) {
	e.CompanyLinkedinURL = companyLinkedinURL
	e.require(employeeFinderRequestFieldCompanyLinkedinURL)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderRequest) SetCountry(country []string) {
	e.Country = country
	e.require(employeeFinderRequestFieldCountry)
}

// SetContinent sets the Continent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderRequest) SetContinent(continent []string) {
	e.Continent = continent
	e.require(employeeFinderRequestFieldContinent)
}

// SetSalesRegion sets the SalesRegion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderRequest) SetSalesRegion(salesRegion []string) {
	e.SalesRegion = salesRegion
	e.require(employeeFinderRequestFieldSalesRegion)
}

// SetJobLevel sets the JobLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderRequest) SetJobLevel(jobLevel []string) {
	e.JobLevel = jobLevel
	e.require(employeeFinderRequestFieldJobLevel)
}

// SetJobFunction sets the JobFunction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderRequest) SetJobFunction(jobFunction []string) {
	e.JobFunction = jobFunction
	e.require(employeeFinderRequestFieldJobFunction)
}

// SetMaxResults sets the MaxResults field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderRequest) SetMaxResults(maxResults *int) {
	e.MaxResults = maxResults
	e.require(employeeFinderRequestFieldMaxResults)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderRequest) SetPage(page *int) {
	e.Page = page
	e.require(employeeFinderRequestFieldPage)
}

func (e *EmployeeFinderRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler EmployeeFinderRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*e = EmployeeFinderRequest(body)
	return nil
}

func (e *EmployeeFinderRequest) MarshalJSON() ([]byte, error) {
	type embed EmployeeFinderRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	employeeFinderResponseFieldSuccess = big.NewInt(1 << 0)
	employeeFinderResponseFieldData    = big.NewInt(1 << 1)
	employeeFinderResponseFieldMeta    = big.NewInt(1 << 2)
)

type EmployeeFinderResponse struct {
	Success bool                        `json:"success" url:"success"`
	Data    *EmployeeFinderResponseData `json:"data" url:"data"`
	Meta    *EmployeeFinderResponseMeta `json:"meta,omitempty" url:"meta,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EmployeeFinderResponse) GetSuccess() bool {
	if e == nil {
		return false
	}
	return e.Success
}

func (e *EmployeeFinderResponse) GetData() *EmployeeFinderResponseData {
	if e == nil {
		return nil
	}
	return e.Data
}

func (e *EmployeeFinderResponse) GetMeta() *EmployeeFinderResponseMeta {
	if e == nil {
		return nil
	}
	return e.Meta
}

func (e *EmployeeFinderResponse) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EmployeeFinderResponse) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponse) SetSuccess(success bool) {
	e.Success = success
	e.require(employeeFinderResponseFieldSuccess)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponse) SetData(data *EmployeeFinderResponseData) {
	e.Data = data
	e.require(employeeFinderResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponse) SetMeta(meta *EmployeeFinderResponseMeta) {
	e.Meta = meta
	e.require(employeeFinderResponseFieldMeta)
}

func (e *EmployeeFinderResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler EmployeeFinderResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EmployeeFinderResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EmployeeFinderResponse) MarshalJSON() ([]byte, error) {
	type embed EmployeeFinderResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EmployeeFinderResponse) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	employeeFinderResponseDataFieldCompanyLinkedinURL = big.NewInt(1 << 0)
	employeeFinderResponseDataFieldMaxResults         = big.NewInt(1 << 1)
	employeeFinderResponseDataFieldResultsLength      = big.NewInt(1 << 2)
	employeeFinderResponseDataFieldPage               = big.NewInt(1 << 3)
	employeeFinderResponseDataFieldTotalPages         = big.NewInt(1 << 4)
	employeeFinderResponseDataFieldTotalResults       = big.NewInt(1 << 5)
	employeeFinderResponseDataFieldResults            = big.NewInt(1 << 6)
)

type EmployeeFinderResponseData struct {
	// The company LinkedIn URL that was searched
	CompanyLinkedinURL string `json:"company_linkedin_url" url:"company_linkedin_url"`
	// Max results per page
	MaxResults int `json:"max_results" url:"max_results"`
	// Number of results in this page
	ResultsLength int `json:"results_length" url:"results_length"`
	// Current page number
	Page int `json:"page" url:"page"`
	// Total pages available
	TotalPages int `json:"total_pages" url:"total_pages"`
	// Total results matching filters
	TotalResults int                                      `json:"total_results" url:"total_results"`
	Results      []*EmployeeFinderResponseDataResultsItem `json:"results" url:"results"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EmployeeFinderResponseData) GetCompanyLinkedinURL() string {
	if e == nil {
		return ""
	}
	return e.CompanyLinkedinURL
}

func (e *EmployeeFinderResponseData) GetMaxResults() int {
	if e == nil {
		return 0
	}
	return e.MaxResults
}

func (e *EmployeeFinderResponseData) GetResultsLength() int {
	if e == nil {
		return 0
	}
	return e.ResultsLength
}

func (e *EmployeeFinderResponseData) GetPage() int {
	if e == nil {
		return 0
	}
	return e.Page
}

func (e *EmployeeFinderResponseData) GetTotalPages() int {
	if e == nil {
		return 0
	}
	return e.TotalPages
}

func (e *EmployeeFinderResponseData) GetTotalResults() int {
	if e == nil {
		return 0
	}
	return e.TotalResults
}

func (e *EmployeeFinderResponseData) GetResults() []*EmployeeFinderResponseDataResultsItem {
	if e == nil {
		return nil
	}
	return e.Results
}

func (e *EmployeeFinderResponseData) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EmployeeFinderResponseData) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetCompanyLinkedinURL sets the CompanyLinkedinURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseData) SetCompanyLinkedinURL(companyLinkedinURL string) {
	e.CompanyLinkedinURL = companyLinkedinURL
	e.require(employeeFinderResponseDataFieldCompanyLinkedinURL)
}

// SetMaxResults sets the MaxResults field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseData) SetMaxResults(maxResults int) {
	e.MaxResults = maxResults
	e.require(employeeFinderResponseDataFieldMaxResults)
}

// SetResultsLength sets the ResultsLength field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseData) SetResultsLength(resultsLength int) {
	e.ResultsLength = resultsLength
	e.require(employeeFinderResponseDataFieldResultsLength)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseData) SetPage(page int) {
	e.Page = page
	e.require(employeeFinderResponseDataFieldPage)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseData) SetTotalPages(totalPages int) {
	e.TotalPages = totalPages
	e.require(employeeFinderResponseDataFieldTotalPages)
}

// SetTotalResults sets the TotalResults field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseData) SetTotalResults(totalResults int) {
	e.TotalResults = totalResults
	e.require(employeeFinderResponseDataFieldTotalResults)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseData) SetResults(results []*EmployeeFinderResponseDataResultsItem) {
	e.Results = results
	e.require(employeeFinderResponseDataFieldResults)
}

func (e *EmployeeFinderResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler EmployeeFinderResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EmployeeFinderResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EmployeeFinderResponseData) MarshalJSON() ([]byte, error) {
	type embed EmployeeFinderResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EmployeeFinderResponseData) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	employeeFinderResponseDataResultsItemFieldFirstName      = big.NewInt(1 << 0)
	employeeFinderResponseDataResultsItemFieldLastName       = big.NewInt(1 << 1)
	employeeFinderResponseDataResultsItemFieldFullName       = big.NewInt(1 << 2)
	employeeFinderResponseDataResultsItemFieldHeadline       = big.NewInt(1 << 3)
	employeeFinderResponseDataResultsItemFieldAboutMe        = big.NewInt(1 << 4)
	employeeFinderResponseDataResultsItemFieldLocation       = big.NewInt(1 << 5)
	employeeFinderResponseDataResultsItemFieldLinkedinURL    = big.NewInt(1 << 6)
	employeeFinderResponseDataResultsItemFieldJobTitle       = big.NewInt(1 << 7)
	employeeFinderResponseDataResultsItemFieldJobLevel       = big.NewInt(1 << 8)
	employeeFinderResponseDataResultsItemFieldJobFunction    = big.NewInt(1 << 9)
	employeeFinderResponseDataResultsItemFieldJobIsCurrent   = big.NewInt(1 << 10)
	employeeFinderResponseDataResultsItemFieldEducation      = big.NewInt(1 << 11)
	employeeFinderResponseDataResultsItemFieldSkills         = big.NewInt(1 << 12)
	employeeFinderResponseDataResultsItemFieldCertifications = big.NewInt(1 << 13)
)

type EmployeeFinderResponseDataResultsItem struct {
	FirstName      *string                                        `json:"first_name,omitempty" url:"first_name,omitempty"`
	LastName       *string                                        `json:"last_name,omitempty" url:"last_name,omitempty"`
	FullName       *string                                        `json:"full_name,omitempty" url:"full_name,omitempty"`
	Headline       *string                                        `json:"headline,omitempty" url:"headline,omitempty"`
	AboutMe        *string                                        `json:"about_me,omitempty" url:"about_me,omitempty"`
	Location       *EmployeeFinderResponseDataResultsItemLocation `json:"location,omitempty" url:"location,omitempty"`
	LinkedinURL    *string                                        `json:"linkedin_url,omitempty" url:"linkedin_url,omitempty"`
	JobTitle       *string                                        `json:"job_title,omitempty" url:"job_title,omitempty"`
	JobLevel       *string                                        `json:"job_level,omitempty" url:"job_level,omitempty"`
	JobFunction    *string                                        `json:"job_function,omitempty" url:"job_function,omitempty"`
	JobIsCurrent   *bool                                          `json:"job_is_current,omitempty" url:"job_is_current,omitempty"`
	Education      *string                                        `json:"education,omitempty" url:"education,omitempty"`
	Skills         *string                                        `json:"skills,omitempty" url:"skills,omitempty"`
	Certifications *string                                        `json:"certifications,omitempty" url:"certifications,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EmployeeFinderResponseDataResultsItem) GetFirstName() *string {
	if e == nil {
		return nil
	}
	return e.FirstName
}

func (e *EmployeeFinderResponseDataResultsItem) GetLastName() *string {
	if e == nil {
		return nil
	}
	return e.LastName
}

func (e *EmployeeFinderResponseDataResultsItem) GetFullName() *string {
	if e == nil {
		return nil
	}
	return e.FullName
}

func (e *EmployeeFinderResponseDataResultsItem) GetHeadline() *string {
	if e == nil {
		return nil
	}
	return e.Headline
}

func (e *EmployeeFinderResponseDataResultsItem) GetAboutMe() *string {
	if e == nil {
		return nil
	}
	return e.AboutMe
}

func (e *EmployeeFinderResponseDataResultsItem) GetLocation() *EmployeeFinderResponseDataResultsItemLocation {
	if e == nil {
		return nil
	}
	return e.Location
}

func (e *EmployeeFinderResponseDataResultsItem) GetLinkedinURL() *string {
	if e == nil {
		return nil
	}
	return e.LinkedinURL
}

func (e *EmployeeFinderResponseDataResultsItem) GetJobTitle() *string {
	if e == nil {
		return nil
	}
	return e.JobTitle
}

func (e *EmployeeFinderResponseDataResultsItem) GetJobLevel() *string {
	if e == nil {
		return nil
	}
	return e.JobLevel
}

func (e *EmployeeFinderResponseDataResultsItem) GetJobFunction() *string {
	if e == nil {
		return nil
	}
	return e.JobFunction
}

func (e *EmployeeFinderResponseDataResultsItem) GetJobIsCurrent() *bool {
	if e == nil {
		return nil
	}
	return e.JobIsCurrent
}

func (e *EmployeeFinderResponseDataResultsItem) GetEducation() *string {
	if e == nil {
		return nil
	}
	return e.Education
}

func (e *EmployeeFinderResponseDataResultsItem) GetSkills() *string {
	if e == nil {
		return nil
	}
	return e.Skills
}

func (e *EmployeeFinderResponseDataResultsItem) GetCertifications() *string {
	if e == nil {
		return nil
	}
	return e.Certifications
}

func (e *EmployeeFinderResponseDataResultsItem) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EmployeeFinderResponseDataResultsItem) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetFirstName sets the FirstName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetFirstName(firstName *string) {
	e.FirstName = firstName
	e.require(employeeFinderResponseDataResultsItemFieldFirstName)
}

// SetLastName sets the LastName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetLastName(lastName *string) {
	e.LastName = lastName
	e.require(employeeFinderResponseDataResultsItemFieldLastName)
}

// SetFullName sets the FullName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetFullName(fullName *string) {
	e.FullName = fullName
	e.require(employeeFinderResponseDataResultsItemFieldFullName)
}

// SetHeadline sets the Headline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetHeadline(headline *string) {
	e.Headline = headline
	e.require(employeeFinderResponseDataResultsItemFieldHeadline)
}

// SetAboutMe sets the AboutMe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetAboutMe(aboutMe *string) {
	e.AboutMe = aboutMe
	e.require(employeeFinderResponseDataResultsItemFieldAboutMe)
}

// SetLocation sets the Location field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetLocation(location *EmployeeFinderResponseDataResultsItemLocation) {
	e.Location = location
	e.require(employeeFinderResponseDataResultsItemFieldLocation)
}

// SetLinkedinURL sets the LinkedinURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetLinkedinURL(linkedinURL *string) {
	e.LinkedinURL = linkedinURL
	e.require(employeeFinderResponseDataResultsItemFieldLinkedinURL)
}

// SetJobTitle sets the JobTitle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetJobTitle(jobTitle *string) {
	e.JobTitle = jobTitle
	e.require(employeeFinderResponseDataResultsItemFieldJobTitle)
}

// SetJobLevel sets the JobLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetJobLevel(jobLevel *string) {
	e.JobLevel = jobLevel
	e.require(employeeFinderResponseDataResultsItemFieldJobLevel)
}

// SetJobFunction sets the JobFunction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetJobFunction(jobFunction *string) {
	e.JobFunction = jobFunction
	e.require(employeeFinderResponseDataResultsItemFieldJobFunction)
}

// SetJobIsCurrent sets the JobIsCurrent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetJobIsCurrent(jobIsCurrent *bool) {
	e.JobIsCurrent = jobIsCurrent
	e.require(employeeFinderResponseDataResultsItemFieldJobIsCurrent)
}

// SetEducation sets the Education field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetEducation(education *string) {
	e.Education = education
	e.require(employeeFinderResponseDataResultsItemFieldEducation)
}

// SetSkills sets the Skills field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetSkills(skills *string) {
	e.Skills = skills
	e.require(employeeFinderResponseDataResultsItemFieldSkills)
}

// SetCertifications sets the Certifications field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItem) SetCertifications(certifications *string) {
	e.Certifications = certifications
	e.require(employeeFinderResponseDataResultsItemFieldCertifications)
}

func (e *EmployeeFinderResponseDataResultsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler EmployeeFinderResponseDataResultsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EmployeeFinderResponseDataResultsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EmployeeFinderResponseDataResultsItem) MarshalJSON() ([]byte, error) {
	type embed EmployeeFinderResponseDataResultsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EmployeeFinderResponseDataResultsItem) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	employeeFinderResponseDataResultsItemLocationFieldCity        = big.NewInt(1 << 0)
	employeeFinderResponseDataResultsItemLocationFieldStateCode   = big.NewInt(1 << 1)
	employeeFinderResponseDataResultsItemLocationFieldCountry     = big.NewInt(1 << 2)
	employeeFinderResponseDataResultsItemLocationFieldCountryCode = big.NewInt(1 << 3)
	employeeFinderResponseDataResultsItemLocationFieldContinent   = big.NewInt(1 << 4)
)

type EmployeeFinderResponseDataResultsItemLocation struct {
	City        *string `json:"city,omitempty" url:"city,omitempty"`
	StateCode   *string `json:"state_code,omitempty" url:"state_code,omitempty"`
	Country     *string `json:"country,omitempty" url:"country,omitempty"`
	CountryCode *string `json:"country_code,omitempty" url:"country_code,omitempty"`
	Continent   *string `json:"continent,omitempty" url:"continent,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EmployeeFinderResponseDataResultsItemLocation) GetCity() *string {
	if e == nil {
		return nil
	}
	return e.City
}

func (e *EmployeeFinderResponseDataResultsItemLocation) GetStateCode() *string {
	if e == nil {
		return nil
	}
	return e.StateCode
}

func (e *EmployeeFinderResponseDataResultsItemLocation) GetCountry() *string {
	if e == nil {
		return nil
	}
	return e.Country
}

func (e *EmployeeFinderResponseDataResultsItemLocation) GetCountryCode() *string {
	if e == nil {
		return nil
	}
	return e.CountryCode
}

func (e *EmployeeFinderResponseDataResultsItemLocation) GetContinent() *string {
	if e == nil {
		return nil
	}
	return e.Continent
}

func (e *EmployeeFinderResponseDataResultsItemLocation) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EmployeeFinderResponseDataResultsItemLocation) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItemLocation) SetCity(city *string) {
	e.City = city
	e.require(employeeFinderResponseDataResultsItemLocationFieldCity)
}

// SetStateCode sets the StateCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItemLocation) SetStateCode(stateCode *string) {
	e.StateCode = stateCode
	e.require(employeeFinderResponseDataResultsItemLocationFieldStateCode)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItemLocation) SetCountry(country *string) {
	e.Country = country
	e.require(employeeFinderResponseDataResultsItemLocationFieldCountry)
}

// SetCountryCode sets the CountryCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItemLocation) SetCountryCode(countryCode *string) {
	e.CountryCode = countryCode
	e.require(employeeFinderResponseDataResultsItemLocationFieldCountryCode)
}

// SetContinent sets the Continent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseDataResultsItemLocation) SetContinent(continent *string) {
	e.Continent = continent
	e.require(employeeFinderResponseDataResultsItemLocationFieldContinent)
}

func (e *EmployeeFinderResponseDataResultsItemLocation) UnmarshalJSON(data []byte) error {
	type unmarshaler EmployeeFinderResponseDataResultsItemLocation
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EmployeeFinderResponseDataResultsItemLocation(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EmployeeFinderResponseDataResultsItemLocation) MarshalJSON() ([]byte, error) {
	type embed EmployeeFinderResponseDataResultsItemLocation
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EmployeeFinderResponseDataResultsItemLocation) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	employeeFinderResponseMetaFieldRequestID        = big.NewInt(1 << 0)
	employeeFinderResponseMetaFieldCreditsUsed      = big.NewInt(1 << 1)
	employeeFinderResponseMetaFieldCreditsRemaining = big.NewInt(1 << 2)
)

type EmployeeFinderResponseMeta struct {
	RequestID *string `json:"requestId,omitempty" url:"requestId,omitempty"`
	// Credits charged (1 per result returned, 0 if no results)
	CreditsUsed *int `json:"creditsUsed,omitempty" url:"creditsUsed,omitempty"`
	// Remaining credit balance
	CreditsRemaining *int `json:"creditsRemaining,omitempty" url:"creditsRemaining,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EmployeeFinderResponseMeta) GetRequestID() *string {
	if e == nil {
		return nil
	}
	return e.RequestID
}

func (e *EmployeeFinderResponseMeta) GetCreditsUsed() *int {
	if e == nil {
		return nil
	}
	return e.CreditsUsed
}

func (e *EmployeeFinderResponseMeta) GetCreditsRemaining() *int {
	if e == nil {
		return nil
	}
	return e.CreditsRemaining
}

func (e *EmployeeFinderResponseMeta) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EmployeeFinderResponseMeta) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseMeta) SetRequestID(requestID *string) {
	e.RequestID = requestID
	e.require(employeeFinderResponseMetaFieldRequestID)
}

// SetCreditsUsed sets the CreditsUsed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseMeta) SetCreditsUsed(creditsUsed *int) {
	e.CreditsUsed = creditsUsed
	e.require(employeeFinderResponseMetaFieldCreditsUsed)
}

// SetCreditsRemaining sets the CreditsRemaining field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EmployeeFinderResponseMeta) SetCreditsRemaining(creditsRemaining *int) {
	e.CreditsRemaining = creditsRemaining
	e.require(employeeFinderResponseMetaFieldCreditsRemaining)
}

func (e *EmployeeFinderResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler EmployeeFinderResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EmployeeFinderResponseMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EmployeeFinderResponseMeta) MarshalJSON() ([]byte, error) {
	type embed EmployeeFinderResponseMeta
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EmployeeFinderResponseMeta) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	waterfallIcpSearchRequestCascadeItemFieldIncludeTitle          = big.NewInt(1 << 0)
	waterfallIcpSearchRequestCascadeItemFieldExcludeTitle          = big.NewInt(1 << 1)
	waterfallIcpSearchRequestCascadeItemFieldJobLevels             = big.NewInt(1 << 2)
	waterfallIcpSearchRequestCascadeItemFieldJobFunctions          = big.NewInt(1 << 3)
	waterfallIcpSearchRequestCascadeItemFieldSkills                = big.NewInt(1 << 4)
	waterfallIcpSearchRequestCascadeItemFieldLocation              = big.NewInt(1 << 5)
	waterfallIcpSearchRequestCascadeItemFieldIncludeHeadlineSearch = big.NewInt(1 << 6)
	waterfallIcpSearchRequestCascadeItemFieldPriorityBonus         = big.NewInt(1 << 7)
)

type WaterfallIcpSearchRequestCascadeItem struct {
	// Job titles to include (case-insensitive exact match or headline search)
	IncludeTitle []string `json:"include_title,omitempty" url:"include_title,omitempty"`
	// Job titles to exclude (case-insensitive)
	ExcludeTitle []string `json:"exclude_title,omitempty" url:"exclude_title,omitempty"`
	// Job seniority levels to filter (e.g. Owner, Founder, C-Level, Partner, VP, Director, Manager, Senior, Staff, Entry, Intern)
	JobLevels []string `json:"job_levels,omitempty" url:"job_levels,omitempty"`
	// Job function areas to filter (e.g. Engineering, Marketing, Sales, Technology)
	JobFunctions []string `json:"job_functions,omitempty" url:"job_functions,omitempty"`
	// Skills to match against candidate profiles (fuzzy substring matching)
	Skills []string `json:"skills,omitempty" url:"skills,omitempty"`
	// Location codes: ISO 3166-1 alpha-2 country codes (US, UK, DE, etc.), continent codes (NORTH_AMERICA, EUROPE, ASIA, etc.), or "WORLD" for any location
	Location []string `json:"location,omitempty" url:"location,omitempty"`
	// When true, also search LinkedIn headline for include_title terms (in addition to job title)
	IncludeHeadlineSearch *bool `json:"include_headline_search,omitempty" url:"include_headline_search,omitempty"`
	// Seniority priority bonus (0-30). Higher = ranked above other cascade levels at equal match quality
	PriorityBonus *int `json:"priority_bonus,omitempty" url:"priority_bonus,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WaterfallIcpSearchRequestCascadeItem) GetIncludeTitle() []string {
	if w == nil {
		return nil
	}
	return w.IncludeTitle
}

func (w *WaterfallIcpSearchRequestCascadeItem) GetExcludeTitle() []string {
	if w == nil {
		return nil
	}
	return w.ExcludeTitle
}

func (w *WaterfallIcpSearchRequestCascadeItem) GetJobLevels() []string {
	if w == nil {
		return nil
	}
	return w.JobLevels
}

func (w *WaterfallIcpSearchRequestCascadeItem) GetJobFunctions() []string {
	if w == nil {
		return nil
	}
	return w.JobFunctions
}

func (w *WaterfallIcpSearchRequestCascadeItem) GetSkills() []string {
	if w == nil {
		return nil
	}
	return w.Skills
}

func (w *WaterfallIcpSearchRequestCascadeItem) GetLocation() []string {
	if w == nil {
		return nil
	}
	return w.Location
}

func (w *WaterfallIcpSearchRequestCascadeItem) GetIncludeHeadlineSearch() *bool {
	if w == nil {
		return nil
	}
	return w.IncludeHeadlineSearch
}

func (w *WaterfallIcpSearchRequestCascadeItem) GetPriorityBonus() *int {
	if w == nil {
		return nil
	}
	return w.PriorityBonus
}

func (w *WaterfallIcpSearchRequestCascadeItem) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WaterfallIcpSearchRequestCascadeItem) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetIncludeTitle sets the IncludeTitle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchRequestCascadeItem) SetIncludeTitle(includeTitle []string) {
	w.IncludeTitle = includeTitle
	w.require(waterfallIcpSearchRequestCascadeItemFieldIncludeTitle)
}

// SetExcludeTitle sets the ExcludeTitle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchRequestCascadeItem) SetExcludeTitle(excludeTitle []string) {
	w.ExcludeTitle = excludeTitle
	w.require(waterfallIcpSearchRequestCascadeItemFieldExcludeTitle)
}

// SetJobLevels sets the JobLevels field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchRequestCascadeItem) SetJobLevels(jobLevels []string) {
	w.JobLevels = jobLevels
	w.require(waterfallIcpSearchRequestCascadeItemFieldJobLevels)
}

// SetJobFunctions sets the JobFunctions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchRequestCascadeItem) SetJobFunctions(jobFunctions []string) {
	w.JobFunctions = jobFunctions
	w.require(waterfallIcpSearchRequestCascadeItemFieldJobFunctions)
}

// SetSkills sets the Skills field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchRequestCascadeItem) SetSkills(skills []string) {
	w.Skills = skills
	w.require(waterfallIcpSearchRequestCascadeItemFieldSkills)
}

// SetLocation sets the Location field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchRequestCascadeItem) SetLocation(location []string) {
	w.Location = location
	w.require(waterfallIcpSearchRequestCascadeItemFieldLocation)
}

// SetIncludeHeadlineSearch sets the IncludeHeadlineSearch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchRequestCascadeItem) SetIncludeHeadlineSearch(includeHeadlineSearch *bool) {
	w.IncludeHeadlineSearch = includeHeadlineSearch
	w.require(waterfallIcpSearchRequestCascadeItemFieldIncludeHeadlineSearch)
}

// SetPriorityBonus sets the PriorityBonus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchRequestCascadeItem) SetPriorityBonus(priorityBonus *int) {
	w.PriorityBonus = priorityBonus
	w.require(waterfallIcpSearchRequestCascadeItemFieldPriorityBonus)
}

func (w *WaterfallIcpSearchRequestCascadeItem) UnmarshalJSON(data []byte) error {
	type unmarshaler WaterfallIcpSearchRequestCascadeItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WaterfallIcpSearchRequestCascadeItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WaterfallIcpSearchRequestCascadeItem) MarshalJSON() ([]byte, error) {
	type embed WaterfallIcpSearchRequestCascadeItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WaterfallIcpSearchRequestCascadeItem) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	waterfallIcpSearchResponseFieldSuccess = big.NewInt(1 << 0)
	waterfallIcpSearchResponseFieldData    = big.NewInt(1 << 1)
	waterfallIcpSearchResponseFieldMeta    = big.NewInt(1 << 2)
)

type WaterfallIcpSearchResponse struct {
	Success bool                            `json:"success" url:"success"`
	Data    *WaterfallIcpSearchResponseData `json:"data" url:"data"`
	Meta    *WaterfallIcpSearchResponseMeta `json:"meta" url:"meta"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WaterfallIcpSearchResponse) GetSuccess() bool {
	if w == nil {
		return false
	}
	return w.Success
}

func (w *WaterfallIcpSearchResponse) GetData() *WaterfallIcpSearchResponseData {
	if w == nil {
		return nil
	}
	return w.Data
}

func (w *WaterfallIcpSearchResponse) GetMeta() *WaterfallIcpSearchResponseMeta {
	if w == nil {
		return nil
	}
	return w.Meta
}

func (w *WaterfallIcpSearchResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WaterfallIcpSearchResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponse) SetSuccess(success bool) {
	w.Success = success
	w.require(waterfallIcpSearchResponseFieldSuccess)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponse) SetData(data *WaterfallIcpSearchResponseData) {
	w.Data = data
	w.require(waterfallIcpSearchResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponse) SetMeta(meta *WaterfallIcpSearchResponseMeta) {
	w.Meta = meta
	w.require(waterfallIcpSearchResponseFieldMeta)
}

func (w *WaterfallIcpSearchResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WaterfallIcpSearchResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WaterfallIcpSearchResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WaterfallIcpSearchResponse) MarshalJSON() ([]byte, error) {
	type embed WaterfallIcpSearchResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WaterfallIcpSearchResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	waterfallIcpSearchResponseDataFieldResults       = big.NewInt(1 << 0)
	waterfallIcpSearchResponseDataFieldTotalFound    = big.NewInt(1 << 1)
	waterfallIcpSearchResponseDataFieldTotalReturned = big.NewInt(1 << 2)
	waterfallIcpSearchResponseDataFieldCascadeStats  = big.NewInt(1 << 3)
)

type WaterfallIcpSearchResponseData struct {
	// Ranked list of matching candidates sorted by ICP score descending
	Results []*WaterfallIcpSearchResponseDataResultsItem `json:"results" url:"results"`
	// Total candidates found across all cascade levels (before min_score filtering)
	TotalFound int `json:"total_found" url:"total_found"`
	// Number of results actually returned after filtering and max_results cap
	TotalReturned int `json:"total_returned" url:"total_returned"`
	// Per-cascade-level statistics showing how many candidates were found and kept
	CascadeStats []*WaterfallIcpSearchResponseDataCascadeStatsItem `json:"cascade_stats" url:"cascade_stats"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WaterfallIcpSearchResponseData) GetResults() []*WaterfallIcpSearchResponseDataResultsItem {
	if w == nil {
		return nil
	}
	return w.Results
}

func (w *WaterfallIcpSearchResponseData) GetTotalFound() int {
	if w == nil {
		return 0
	}
	return w.TotalFound
}

func (w *WaterfallIcpSearchResponseData) GetTotalReturned() int {
	if w == nil {
		return 0
	}
	return w.TotalReturned
}

func (w *WaterfallIcpSearchResponseData) GetCascadeStats() []*WaterfallIcpSearchResponseDataCascadeStatsItem {
	if w == nil {
		return nil
	}
	return w.CascadeStats
}

func (w *WaterfallIcpSearchResponseData) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WaterfallIcpSearchResponseData) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseData) SetResults(results []*WaterfallIcpSearchResponseDataResultsItem) {
	w.Results = results
	w.require(waterfallIcpSearchResponseDataFieldResults)
}

// SetTotalFound sets the TotalFound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseData) SetTotalFound(totalFound int) {
	w.TotalFound = totalFound
	w.require(waterfallIcpSearchResponseDataFieldTotalFound)
}

// SetTotalReturned sets the TotalReturned field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseData) SetTotalReturned(totalReturned int) {
	w.TotalReturned = totalReturned
	w.require(waterfallIcpSearchResponseDataFieldTotalReturned)
}

// SetCascadeStats sets the CascadeStats field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseData) SetCascadeStats(cascadeStats []*WaterfallIcpSearchResponseDataCascadeStatsItem) {
	w.CascadeStats = cascadeStats
	w.require(waterfallIcpSearchResponseDataFieldCascadeStats)
}

func (w *WaterfallIcpSearchResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler WaterfallIcpSearchResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WaterfallIcpSearchResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WaterfallIcpSearchResponseData) MarshalJSON() ([]byte, error) {
	type embed WaterfallIcpSearchResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WaterfallIcpSearchResponseData) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	waterfallIcpSearchResponseDataCascadeStatsItemFieldLevel           = big.NewInt(1 << 0)
	waterfallIcpSearchResponseDataCascadeStatsItemFieldCandidatesFound = big.NewInt(1 << 1)
	waterfallIcpSearchResponseDataCascadeStatsItemFieldCandidatesKept  = big.NewInt(1 << 2)
)

type WaterfallIcpSearchResponseDataCascadeStatsItem struct {
	// Cascade level index (0-based)
	Level int `json:"level" url:"level"`
	// Total candidates returned from ClickHouse for this level
	CandidatesFound int `json:"candidates_found" url:"candidates_found"`
	// Candidates that passed min_score and deduplication
	CandidatesKept int `json:"candidates_kept" url:"candidates_kept"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WaterfallIcpSearchResponseDataCascadeStatsItem) GetLevel() int {
	if w == nil {
		return 0
	}
	return w.Level
}

func (w *WaterfallIcpSearchResponseDataCascadeStatsItem) GetCandidatesFound() int {
	if w == nil {
		return 0
	}
	return w.CandidatesFound
}

func (w *WaterfallIcpSearchResponseDataCascadeStatsItem) GetCandidatesKept() int {
	if w == nil {
		return 0
	}
	return w.CandidatesKept
}

func (w *WaterfallIcpSearchResponseDataCascadeStatsItem) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WaterfallIcpSearchResponseDataCascadeStatsItem) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetLevel sets the Level field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataCascadeStatsItem) SetLevel(level int) {
	w.Level = level
	w.require(waterfallIcpSearchResponseDataCascadeStatsItemFieldLevel)
}

// SetCandidatesFound sets the CandidatesFound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataCascadeStatsItem) SetCandidatesFound(candidatesFound int) {
	w.CandidatesFound = candidatesFound
	w.require(waterfallIcpSearchResponseDataCascadeStatsItemFieldCandidatesFound)
}

// SetCandidatesKept sets the CandidatesKept field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataCascadeStatsItem) SetCandidatesKept(candidatesKept int) {
	w.CandidatesKept = candidatesKept
	w.require(waterfallIcpSearchResponseDataCascadeStatsItemFieldCandidatesKept)
}

func (w *WaterfallIcpSearchResponseDataCascadeStatsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler WaterfallIcpSearchResponseDataCascadeStatsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WaterfallIcpSearchResponseDataCascadeStatsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WaterfallIcpSearchResponseDataCascadeStatsItem) MarshalJSON() ([]byte, error) {
	type embed WaterfallIcpSearchResponseDataCascadeStatsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WaterfallIcpSearchResponseDataCascadeStatsItem) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	waterfallIcpSearchResponseDataResultsItemFieldPerson          = big.NewInt(1 << 0)
	waterfallIcpSearchResponseDataResultsItemFieldCurrentPosition = big.NewInt(1 << 1)
	waterfallIcpSearchResponseDataResultsItemFieldSkills          = big.NewInt(1 << 2)
	waterfallIcpSearchResponseDataResultsItemFieldEducation       = big.NewInt(1 << 3)
	waterfallIcpSearchResponseDataResultsItemFieldCertifications  = big.NewInt(1 << 4)
	waterfallIcpSearchResponseDataResultsItemFieldScore           = big.NewInt(1 << 5)
	waterfallIcpSearchResponseDataResultsItemFieldRanking         = big.NewInt(1 << 6)
	waterfallIcpSearchResponseDataResultsItemFieldCascadeLevel    = big.NewInt(1 << 7)
	waterfallIcpSearchResponseDataResultsItemFieldRankingFactors  = big.NewInt(1 << 8)
	waterfallIcpSearchResponseDataResultsItemFieldWhatMatched     = big.NewInt(1 << 9)
)

type WaterfallIcpSearchResponseDataResultsItem struct {
	// Person identifying information
	Person *WaterfallIcpSearchResponseDataResultsItemPerson `json:"person" url:"person"`
	// Current job position details
	CurrentPosition *WaterfallIcpSearchResponseDataResultsItemCurrentPosition `json:"current_position" url:"current_position"`
	// Parsed skills list from candidate profile
	Skills         []string `json:"skills" url:"skills"`
	Education      *string  `json:"education,omitempty" url:"education,omitempty"`
	Certifications *string  `json:"certifications,omitempty" url:"certifications,omitempty"`
	// Normalized ICP score (0-100). Normalized against only the scoring dimensions that were specified in the cascade level.
	Score float64 `json:"score" url:"score"`
	// Rank position (1-based, sorted by score descending)
	Ranking int `json:"ranking" url:"ranking"`
	// Which cascade level matched this candidate (0-based index)
	CascadeLevel int `json:"cascade_level" url:"cascade_level"`
	// Breakdown of raw points awarded for each scoring dimension
	RankingFactors *WaterfallIcpSearchResponseDataResultsItemRankingFactors `json:"ranking_factors" url:"ranking_factors"`
	// Human-readable list of matching criteria for this candidate
	WhatMatched []string `json:"what_matched" url:"what_matched"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WaterfallIcpSearchResponseDataResultsItem) GetPerson() *WaterfallIcpSearchResponseDataResultsItemPerson {
	if w == nil {
		return nil
	}
	return w.Person
}

func (w *WaterfallIcpSearchResponseDataResultsItem) GetCurrentPosition() *WaterfallIcpSearchResponseDataResultsItemCurrentPosition {
	if w == nil {
		return nil
	}
	return w.CurrentPosition
}

func (w *WaterfallIcpSearchResponseDataResultsItem) GetSkills() []string {
	if w == nil {
		return nil
	}
	return w.Skills
}

func (w *WaterfallIcpSearchResponseDataResultsItem) GetEducation() *string {
	if w == nil {
		return nil
	}
	return w.Education
}

func (w *WaterfallIcpSearchResponseDataResultsItem) GetCertifications() *string {
	if w == nil {
		return nil
	}
	return w.Certifications
}

func (w *WaterfallIcpSearchResponseDataResultsItem) GetScore() float64 {
	if w == nil {
		return 0
	}
	return w.Score
}

func (w *WaterfallIcpSearchResponseDataResultsItem) GetRanking() int {
	if w == nil {
		return 0
	}
	return w.Ranking
}

func (w *WaterfallIcpSearchResponseDataResultsItem) GetCascadeLevel() int {
	if w == nil {
		return 0
	}
	return w.CascadeLevel
}

func (w *WaterfallIcpSearchResponseDataResultsItem) GetRankingFactors() *WaterfallIcpSearchResponseDataResultsItemRankingFactors {
	if w == nil {
		return nil
	}
	return w.RankingFactors
}

func (w *WaterfallIcpSearchResponseDataResultsItem) GetWhatMatched() []string {
	if w == nil {
		return nil
	}
	return w.WhatMatched
}

func (w *WaterfallIcpSearchResponseDataResultsItem) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WaterfallIcpSearchResponseDataResultsItem) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetPerson sets the Person field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItem) SetPerson(person *WaterfallIcpSearchResponseDataResultsItemPerson) {
	w.Person = person
	w.require(waterfallIcpSearchResponseDataResultsItemFieldPerson)
}

// SetCurrentPosition sets the CurrentPosition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItem) SetCurrentPosition(currentPosition *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) {
	w.CurrentPosition = currentPosition
	w.require(waterfallIcpSearchResponseDataResultsItemFieldCurrentPosition)
}

// SetSkills sets the Skills field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItem) SetSkills(skills []string) {
	w.Skills = skills
	w.require(waterfallIcpSearchResponseDataResultsItemFieldSkills)
}

// SetEducation sets the Education field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItem) SetEducation(education *string) {
	w.Education = education
	w.require(waterfallIcpSearchResponseDataResultsItemFieldEducation)
}

// SetCertifications sets the Certifications field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItem) SetCertifications(certifications *string) {
	w.Certifications = certifications
	w.require(waterfallIcpSearchResponseDataResultsItemFieldCertifications)
}

// SetScore sets the Score field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItem) SetScore(score float64) {
	w.Score = score
	w.require(waterfallIcpSearchResponseDataResultsItemFieldScore)
}

// SetRanking sets the Ranking field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItem) SetRanking(ranking int) {
	w.Ranking = ranking
	w.require(waterfallIcpSearchResponseDataResultsItemFieldRanking)
}

// SetCascadeLevel sets the CascadeLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItem) SetCascadeLevel(cascadeLevel int) {
	w.CascadeLevel = cascadeLevel
	w.require(waterfallIcpSearchResponseDataResultsItemFieldCascadeLevel)
}

// SetRankingFactors sets the RankingFactors field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItem) SetRankingFactors(rankingFactors *WaterfallIcpSearchResponseDataResultsItemRankingFactors) {
	w.RankingFactors = rankingFactors
	w.require(waterfallIcpSearchResponseDataResultsItemFieldRankingFactors)
}

// SetWhatMatched sets the WhatMatched field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItem) SetWhatMatched(whatMatched []string) {
	w.WhatMatched = whatMatched
	w.require(waterfallIcpSearchResponseDataResultsItemFieldWhatMatched)
}

func (w *WaterfallIcpSearchResponseDataResultsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler WaterfallIcpSearchResponseDataResultsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WaterfallIcpSearchResponseDataResultsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WaterfallIcpSearchResponseDataResultsItem) MarshalJSON() ([]byte, error) {
	type embed WaterfallIcpSearchResponseDataResultsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WaterfallIcpSearchResponseDataResultsItem) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// Current job position details
var (
	waterfallIcpSearchResponseDataResultsItemCurrentPositionFieldTitle     = big.NewInt(1 << 0)
	waterfallIcpSearchResponseDataResultsItemCurrentPositionFieldCompany   = big.NewInt(1 << 1)
	waterfallIcpSearchResponseDataResultsItemCurrentPositionFieldLevel     = big.NewInt(1 << 2)
	waterfallIcpSearchResponseDataResultsItemCurrentPositionFieldFunction  = big.NewInt(1 << 3)
	waterfallIcpSearchResponseDataResultsItemCurrentPositionFieldIsCurrent = big.NewInt(1 << 4)
	waterfallIcpSearchResponseDataResultsItemCurrentPositionFieldStartDate = big.NewInt(1 << 5)
)

type WaterfallIcpSearchResponseDataResultsItemCurrentPosition struct {
	Title     *string `json:"title,omitempty" url:"title,omitempty"`
	Company   *string `json:"company,omitempty" url:"company,omitempty"`
	Level     *string `json:"level,omitempty" url:"level,omitempty"`
	Function  *string `json:"function,omitempty" url:"function,omitempty"`
	IsCurrent *bool   `json:"is_current,omitempty" url:"is_current,omitempty"`
	// Job start date in YYYY-MM-DD format
	StartDate *string `json:"start_date,omitempty" url:"start_date,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) GetTitle() *string {
	if w == nil {
		return nil
	}
	return w.Title
}

func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) GetCompany() *string {
	if w == nil {
		return nil
	}
	return w.Company
}

func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) GetLevel() *string {
	if w == nil {
		return nil
	}
	return w.Level
}

func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) GetFunction() *string {
	if w == nil {
		return nil
	}
	return w.Function
}

func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) GetIsCurrent() *bool {
	if w == nil {
		return nil
	}
	return w.IsCurrent
}

func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) GetStartDate() *string {
	if w == nil {
		return nil
	}
	return w.StartDate
}

func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) SetTitle(title *string) {
	w.Title = title
	w.require(waterfallIcpSearchResponseDataResultsItemCurrentPositionFieldTitle)
}

// SetCompany sets the Company field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) SetCompany(company *string) {
	w.Company = company
	w.require(waterfallIcpSearchResponseDataResultsItemCurrentPositionFieldCompany)
}

// SetLevel sets the Level field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) SetLevel(level *string) {
	w.Level = level
	w.require(waterfallIcpSearchResponseDataResultsItemCurrentPositionFieldLevel)
}

// SetFunction sets the Function field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) SetFunction(function *string) {
	w.Function = function
	w.require(waterfallIcpSearchResponseDataResultsItemCurrentPositionFieldFunction)
}

// SetIsCurrent sets the IsCurrent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) SetIsCurrent(isCurrent *bool) {
	w.IsCurrent = isCurrent
	w.require(waterfallIcpSearchResponseDataResultsItemCurrentPositionFieldIsCurrent)
}

// SetStartDate sets the StartDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) SetStartDate(startDate *string) {
	w.StartDate = startDate
	w.require(waterfallIcpSearchResponseDataResultsItemCurrentPositionFieldStartDate)
}

func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) UnmarshalJSON(data []byte) error {
	type unmarshaler WaterfallIcpSearchResponseDataResultsItemCurrentPosition
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WaterfallIcpSearchResponseDataResultsItemCurrentPosition(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) MarshalJSON() ([]byte, error) {
	type embed WaterfallIcpSearchResponseDataResultsItemCurrentPosition
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WaterfallIcpSearchResponseDataResultsItemCurrentPosition) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// Person identifying information
var (
	waterfallIcpSearchResponseDataResultsItemPersonFieldFirstName        = big.NewInt(1 << 0)
	waterfallIcpSearchResponseDataResultsItemPersonFieldLastName         = big.NewInt(1 << 1)
	waterfallIcpSearchResponseDataResultsItemPersonFieldLinkedinURL      = big.NewInt(1 << 2)
	waterfallIcpSearchResponseDataResultsItemPersonFieldLinkedinHeadline = big.NewInt(1 << 3)
	waterfallIcpSearchResponseDataResultsItemPersonFieldLocation         = big.NewInt(1 << 4)
	waterfallIcpSearchResponseDataResultsItemPersonFieldEmailDomain      = big.NewInt(1 << 5)
)

type WaterfallIcpSearchResponseDataResultsItemPerson struct {
	FirstName        *string `json:"first_name,omitempty" url:"first_name,omitempty"`
	LastName         *string `json:"last_name,omitempty" url:"last_name,omitempty"`
	LinkedinURL      *string `json:"linkedin_url,omitempty" url:"linkedin_url,omitempty"`
	LinkedinHeadline *string `json:"linkedin_headline,omitempty" url:"linkedin_headline,omitempty"`
	// Concatenation of city, state, and country
	Location    *string `json:"location,omitempty" url:"location,omitempty"`
	EmailDomain *string `json:"email_domain,omitempty" url:"email_domain,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WaterfallIcpSearchResponseDataResultsItemPerson) GetFirstName() *string {
	if w == nil {
		return nil
	}
	return w.FirstName
}

func (w *WaterfallIcpSearchResponseDataResultsItemPerson) GetLastName() *string {
	if w == nil {
		return nil
	}
	return w.LastName
}

func (w *WaterfallIcpSearchResponseDataResultsItemPerson) GetLinkedinURL() *string {
	if w == nil {
		return nil
	}
	return w.LinkedinURL
}

func (w *WaterfallIcpSearchResponseDataResultsItemPerson) GetLinkedinHeadline() *string {
	if w == nil {
		return nil
	}
	return w.LinkedinHeadline
}

func (w *WaterfallIcpSearchResponseDataResultsItemPerson) GetLocation() *string {
	if w == nil {
		return nil
	}
	return w.Location
}

func (w *WaterfallIcpSearchResponseDataResultsItemPerson) GetEmailDomain() *string {
	if w == nil {
		return nil
	}
	return w.EmailDomain
}

func (w *WaterfallIcpSearchResponseDataResultsItemPerson) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WaterfallIcpSearchResponseDataResultsItemPerson) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetFirstName sets the FirstName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemPerson) SetFirstName(firstName *string) {
	w.FirstName = firstName
	w.require(waterfallIcpSearchResponseDataResultsItemPersonFieldFirstName)
}

// SetLastName sets the LastName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemPerson) SetLastName(lastName *string) {
	w.LastName = lastName
	w.require(waterfallIcpSearchResponseDataResultsItemPersonFieldLastName)
}

// SetLinkedinURL sets the LinkedinURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemPerson) SetLinkedinURL(linkedinURL *string) {
	w.LinkedinURL = linkedinURL
	w.require(waterfallIcpSearchResponseDataResultsItemPersonFieldLinkedinURL)
}

// SetLinkedinHeadline sets the LinkedinHeadline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemPerson) SetLinkedinHeadline(linkedinHeadline *string) {
	w.LinkedinHeadline = linkedinHeadline
	w.require(waterfallIcpSearchResponseDataResultsItemPersonFieldLinkedinHeadline)
}

// SetLocation sets the Location field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemPerson) SetLocation(location *string) {
	w.Location = location
	w.require(waterfallIcpSearchResponseDataResultsItemPersonFieldLocation)
}

// SetEmailDomain sets the EmailDomain field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemPerson) SetEmailDomain(emailDomain *string) {
	w.EmailDomain = emailDomain
	w.require(waterfallIcpSearchResponseDataResultsItemPersonFieldEmailDomain)
}

func (w *WaterfallIcpSearchResponseDataResultsItemPerson) UnmarshalJSON(data []byte) error {
	type unmarshaler WaterfallIcpSearchResponseDataResultsItemPerson
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WaterfallIcpSearchResponseDataResultsItemPerson(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WaterfallIcpSearchResponseDataResultsItemPerson) MarshalJSON() ([]byte, error) {
	type embed WaterfallIcpSearchResponseDataResultsItemPerson
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WaterfallIcpSearchResponseDataResultsItemPerson) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// Breakdown of raw points awarded for each scoring dimension
var (
	waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldTitleMatch          = big.NewInt(1 << 0)
	waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldJobLevel            = big.NewInt(1 << 1)
	waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldSkillsOverlap       = big.NewInt(1 << 2)
	waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldLocationMatch       = big.NewInt(1 << 3)
	waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldCurrentJob          = big.NewInt(1 << 4)
	waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldProfileCompleteness = big.NewInt(1 << 5)
	waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldExperience          = big.NewInt(1 << 6)
	waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldPriorityBonus       = big.NewInt(1 << 7)
)

type WaterfallIcpSearchResponseDataResultsItemRankingFactors struct {
	// Points from title matching (max 30). 30=exact, 25=partial/substring, 20=headline, 10=function match
	TitleMatch *float64 `json:"title_match,omitempty" url:"title_match,omitempty"`
	// Points from job level matching (max 20). 20=exact, 10=adjacent ±1, 5=near ±2
	JobLevel *float64 `json:"job_level,omitempty" url:"job_level,omitempty"`
	// Points from skills overlap (max 15). Calculated as (matched/requested) * 15
	SkillsOverlap *float64 `json:"skills_overlap,omitempty" url:"skills_overlap,omitempty"`
	// Points from location matching (max 15). 15=country/WORLD, 7=continent
	LocationMatch *float64 `json:"location_match,omitempty" url:"location_match,omitempty"`
	// Points from current job status (max 10). 10 if JOB_IS_CURRENT_PER is true
	CurrentJob *float64 `json:"current_job,omitempty" url:"current_job,omitempty"`
	// Points from profile completeness (max 5). 1 point each for: linkedin_url, email_domain, skills, education, headline
	ProfileCompleteness *float64 `json:"profile_completeness,omitempty" url:"profile_completeness,omitempty"`
	// Points from job tenure (max 5). 5=>5yr, 4=>3yr, 3=>2yr, 2=>1yr, 1=≤1yr
	Experience *float64 `json:"experience,omitempty" url:"experience,omitempty"`
	// Seniority priority bonus from cascade level (0-30). Higher = ranked above other cascade levels at equal match quality
	PriorityBonus *float64 `json:"priority_bonus,omitempty" url:"priority_bonus,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) GetTitleMatch() *float64 {
	if w == nil {
		return nil
	}
	return w.TitleMatch
}

func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) GetJobLevel() *float64 {
	if w == nil {
		return nil
	}
	return w.JobLevel
}

func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) GetSkillsOverlap() *float64 {
	if w == nil {
		return nil
	}
	return w.SkillsOverlap
}

func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) GetLocationMatch() *float64 {
	if w == nil {
		return nil
	}
	return w.LocationMatch
}

func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) GetCurrentJob() *float64 {
	if w == nil {
		return nil
	}
	return w.CurrentJob
}

func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) GetProfileCompleteness() *float64 {
	if w == nil {
		return nil
	}
	return w.ProfileCompleteness
}

func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) GetExperience() *float64 {
	if w == nil {
		return nil
	}
	return w.Experience
}

func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) GetPriorityBonus() *float64 {
	if w == nil {
		return nil
	}
	return w.PriorityBonus
}

func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetTitleMatch sets the TitleMatch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) SetTitleMatch(titleMatch *float64) {
	w.TitleMatch = titleMatch
	w.require(waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldTitleMatch)
}

// SetJobLevel sets the JobLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) SetJobLevel(jobLevel *float64) {
	w.JobLevel = jobLevel
	w.require(waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldJobLevel)
}

// SetSkillsOverlap sets the SkillsOverlap field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) SetSkillsOverlap(skillsOverlap *float64) {
	w.SkillsOverlap = skillsOverlap
	w.require(waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldSkillsOverlap)
}

// SetLocationMatch sets the LocationMatch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) SetLocationMatch(locationMatch *float64) {
	w.LocationMatch = locationMatch
	w.require(waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldLocationMatch)
}

// SetCurrentJob sets the CurrentJob field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) SetCurrentJob(currentJob *float64) {
	w.CurrentJob = currentJob
	w.require(waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldCurrentJob)
}

// SetProfileCompleteness sets the ProfileCompleteness field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) SetProfileCompleteness(profileCompleteness *float64) {
	w.ProfileCompleteness = profileCompleteness
	w.require(waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldProfileCompleteness)
}

// SetExperience sets the Experience field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) SetExperience(experience *float64) {
	w.Experience = experience
	w.require(waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldExperience)
}

// SetPriorityBonus sets the PriorityBonus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) SetPriorityBonus(priorityBonus *float64) {
	w.PriorityBonus = priorityBonus
	w.require(waterfallIcpSearchResponseDataResultsItemRankingFactorsFieldPriorityBonus)
}

func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) UnmarshalJSON(data []byte) error {
	type unmarshaler WaterfallIcpSearchResponseDataResultsItemRankingFactors
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WaterfallIcpSearchResponseDataResultsItemRankingFactors(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) MarshalJSON() ([]byte, error) {
	type embed WaterfallIcpSearchResponseDataResultsItemRankingFactors
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WaterfallIcpSearchResponseDataResultsItemRankingFactors) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	waterfallIcpSearchResponseMetaFieldRequestID        = big.NewInt(1 << 0)
	waterfallIcpSearchResponseMetaFieldCreditsUsed      = big.NewInt(1 << 1)
	waterfallIcpSearchResponseMetaFieldCreditsRemaining = big.NewInt(1 << 2)
)

type WaterfallIcpSearchResponseMeta struct {
	RequestID *string `json:"requestId,omitempty" url:"requestId,omitempty"`
	// Credits charged for this request (1 per profile returned, 0 if no results)
	CreditsUsed *int `json:"creditsUsed,omitempty" url:"creditsUsed,omitempty"`
	// Remaining credit balance after this request
	CreditsRemaining *int `json:"creditsRemaining,omitempty" url:"creditsRemaining,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WaterfallIcpSearchResponseMeta) GetRequestID() *string {
	if w == nil {
		return nil
	}
	return w.RequestID
}

func (w *WaterfallIcpSearchResponseMeta) GetCreditsUsed() *int {
	if w == nil {
		return nil
	}
	return w.CreditsUsed
}

func (w *WaterfallIcpSearchResponseMeta) GetCreditsRemaining() *int {
	if w == nil {
		return nil
	}
	return w.CreditsRemaining
}

func (w *WaterfallIcpSearchResponseMeta) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WaterfallIcpSearchResponseMeta) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseMeta) SetRequestID(requestID *string) {
	w.RequestID = requestID
	w.require(waterfallIcpSearchResponseMetaFieldRequestID)
}

// SetCreditsUsed sets the CreditsUsed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseMeta) SetCreditsUsed(creditsUsed *int) {
	w.CreditsUsed = creditsUsed
	w.require(waterfallIcpSearchResponseMetaFieldCreditsUsed)
}

// SetCreditsRemaining sets the CreditsRemaining field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchResponseMeta) SetCreditsRemaining(creditsRemaining *int) {
	w.CreditsRemaining = creditsRemaining
	w.require(waterfallIcpSearchResponseMetaFieldCreditsRemaining)
}

func (w *WaterfallIcpSearchResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler WaterfallIcpSearchResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WaterfallIcpSearchResponseMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WaterfallIcpSearchResponseMeta) MarshalJSON() ([]byte, error) {
	type embed WaterfallIcpSearchResponseMeta
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WaterfallIcpSearchResponseMeta) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	waterfallIcpSearchRequestFieldCompanyLinkedinURL = big.NewInt(1 << 0)
	waterfallIcpSearchRequestFieldCascade            = big.NewInt(1 << 1)
	waterfallIcpSearchRequestFieldMaxResults         = big.NewInt(1 << 2)
	waterfallIcpSearchRequestFieldMinScore           = big.NewInt(1 << 3)
)

type WaterfallIcpSearchRequest struct {
	// Company LinkedIn URL to search employees for. Must be a valid LinkedIn company URL.
	CompanyLinkedinURL string `json:"company_linkedin_url" url:"-"`
	// Cascading ICP filter levels, processed in order. Results from earlier levels are excluded from later ones (deduplication by RBID_PER). If omitted, uses a default 4-level cascade: CEO/Founder → C-Suite → VP → Director.
	Cascade []*WaterfallIcpSearchRequestCascadeItem `json:"cascade,omitempty" url:"-"`
	// Maximum total results to return across all cascade levels
	MaxResults *int `json:"max_results,omitempty" url:"-"`
	// Minimum ICP score threshold (0-100). Candidates scoring below this are filtered out.
	MinScore *float64 `json:"min_score,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WaterfallIcpSearchRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetCompanyLinkedinURL sets the CompanyLinkedinURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchRequest) SetCompanyLinkedinURL(companyLinkedinURL string) {
	w.CompanyLinkedinURL = companyLinkedinURL
	w.require(waterfallIcpSearchRequestFieldCompanyLinkedinURL)
}

// SetCascade sets the Cascade field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchRequest) SetCascade(cascade []*WaterfallIcpSearchRequestCascadeItem) {
	w.Cascade = cascade
	w.require(waterfallIcpSearchRequestFieldCascade)
}

// SetMaxResults sets the MaxResults field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchRequest) SetMaxResults(maxResults *int) {
	w.MaxResults = maxResults
	w.require(waterfallIcpSearchRequestFieldMaxResults)
}

// SetMinScore sets the MinScore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WaterfallIcpSearchRequest) SetMinScore(minScore *float64) {
	w.MinScore = minScore
	w.require(waterfallIcpSearchRequestFieldMinScore)
}

func (w *WaterfallIcpSearchRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler WaterfallIcpSearchRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*w = WaterfallIcpSearchRequest(body)
	return nil
}

func (w *WaterfallIcpSearchRequest) MarshalJSON() ([]byte, error) {
	type embed WaterfallIcpSearchRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}
