// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "github.com/maximiseai/enrich-go-sdk/internal"
)

var (
	phoneBatchRequestFieldEmails     = big.NewInt(1 << 0)
	phoneBatchRequestFieldLinkedins  = big.NewInt(1 << 1)
	phoneBatchRequestFieldWebhookURL = big.NewInt(1 << 2)
)

type PhoneBatchRequest struct {
	// Email addresses to look up
	Emails []string `json:"emails,omitempty" url:"-"`
	// Profile URLs to look up
	Linkedins []string `json:"linkedins,omitempty" url:"-"`
	// A URL on your server where we should send webhook callbacks.
	// You'll receive one POST per item, plus one final completion POST.
	WebhookURL *string `json:"webhookUrl,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PhoneBatchRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetEmails sets the Emails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBatchRequest) SetEmails(emails []string) {
	p.Emails = emails
	p.require(phoneBatchRequestFieldEmails)
}

// SetLinkedins sets the Linkedins field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBatchRequest) SetLinkedins(linkedins []string) {
	p.Linkedins = linkedins
	p.require(phoneBatchRequestFieldLinkedins)
}

// SetWebhookURL sets the WebhookURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBatchRequest) SetWebhookURL(webhookURL *string) {
	p.WebhookURL = webhookURL
	p.require(phoneBatchRequestFieldWebhookURL)
}

func (p *PhoneBatchRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneBatchRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PhoneBatchRequest(body)
	return nil
}

func (p *PhoneBatchRequest) MarshalJSON() ([]byte, error) {
	type embed PhoneBatchRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getPhoneBulkJobResultsRequestFieldJobID = big.NewInt(1 << 0)
	getPhoneBulkJobResultsRequestFieldPage  = big.NewInt(1 << 1)
	getPhoneBulkJobResultsRequestFieldLimit = big.NewInt(1 << 2)
)

type GetPhoneBulkJobResultsRequest struct {
	// The job identifier (24-character hex string) returned when you submitted the job
	JobID string `json:"-" url:"-"`
	// Page number (default: 1)
	Page *int `json:"-" url:"page,omitempty"`
	// Results per page (default: 100, max: 1 000)
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPhoneBulkJobResultsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetJobID sets the JobID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneBulkJobResultsRequest) SetJobID(jobID string) {
	g.JobID = jobID
	g.require(getPhoneBulkJobResultsRequestFieldJobID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneBulkJobResultsRequest) SetPage(page *int) {
	g.Page = page
	g.require(getPhoneBulkJobResultsRequestFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneBulkJobResultsRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getPhoneBulkJobResultsRequestFieldLimit)
}

var (
	getPhoneBulkJobStatusRequestFieldJobID = big.NewInt(1 << 0)
)

type GetPhoneBulkJobStatusRequest struct {
	// The job identifier (24-character hex string) returned when you submitted the job
	JobID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPhoneBulkJobStatusRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetJobID sets the JobID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneBulkJobStatusRequest) SetJobID(jobID string) {
	g.JobID = jobID
	g.require(getPhoneBulkJobStatusRequestFieldJobID)
}

var (
	phoneLookupRequestFieldEmail    = big.NewInt(1 << 0)
	phoneLookupRequestFieldLinkedin = big.NewInt(1 << 1)
)

type PhoneLookupRequest struct {
	// The person's email address
	Email *string `json:"-" url:"email,omitempty"`
	// The person's profile URL
	Linkedin *string `json:"-" url:"linkedin,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PhoneLookupRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneLookupRequest) SetEmail(email *string) {
	p.Email = email
	p.require(phoneLookupRequestFieldEmail)
}

// SetLinkedin sets the Linkedin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneLookupRequest) SetLinkedin(linkedin *string) {
	p.Linkedin = linkedin
	p.require(phoneLookupRequestFieldLinkedin)
}

var (
	phoneBulkJobResultsResponseFieldData = big.NewInt(1 << 0)
	phoneBulkJobResultsResponseFieldMeta = big.NewInt(1 << 1)
)

type PhoneBulkJobResultsResponse struct {
	Data *PhoneBulkJobResultsResponseData `json:"data" url:"data"`
	Meta *BatchResultsMeta                `json:"meta,omitempty" url:"meta,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	success        bool

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneBulkJobResultsResponse) GetData() *PhoneBulkJobResultsResponseData {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PhoneBulkJobResultsResponse) GetMeta() *BatchResultsMeta {
	if p == nil {
		return nil
	}
	return p.Meta
}

func (p *PhoneBulkJobResultsResponse) Success() bool {
	return p.success
}

func (p *PhoneBulkJobResultsResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PhoneBulkJobResultsResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobResultsResponse) SetData(data *PhoneBulkJobResultsResponseData) {
	p.Data = data
	p.require(phoneBulkJobResultsResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobResultsResponse) SetMeta(meta *BatchResultsMeta) {
	p.Meta = meta
	p.require(phoneBulkJobResultsResponseFieldMeta)
}

func (p *PhoneBulkJobResultsResponse) UnmarshalJSON(data []byte) error {
	type embed PhoneBulkJobResultsResponse
	var unmarshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PhoneBulkJobResultsResponse(unmarshaler.embed)
	if unmarshaler.Success != true {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", p, true, unmarshaler.Success)
	}
	p.success = unmarshaler.Success
	extraProperties, err := internal.ExtractExtraProperties(data, *p, "success")
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneBulkJobResultsResponse) MarshalJSON() ([]byte, error) {
	type embed PhoneBulkJobResultsResponse
	var marshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed:   embed(*p),
		Success: true,
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneBulkJobResultsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	phoneBulkJobResultsResponseDataFieldBatchID        = big.NewInt(1 << 0)
	phoneBulkJobResultsResponseDataFieldStatus         = big.NewInt(1 << 1)
	phoneBulkJobResultsResponseDataFieldTotalItems     = big.NewInt(1 << 2)
	phoneBulkJobResultsResponseDataFieldProcessedItems = big.NewInt(1 << 3)
	phoneBulkJobResultsResponseDataFieldSuccessful     = big.NewInt(1 << 4)
	phoneBulkJobResultsResponseDataFieldFailed         = big.NewInt(1 << 5)
	phoneBulkJobResultsResponseDataFieldResults        = big.NewInt(1 << 6)
	phoneBulkJobResultsResponseDataFieldPage           = big.NewInt(1 << 7)
	phoneBulkJobResultsResponseDataFieldLimit          = big.NewInt(1 << 8)
)

type PhoneBulkJobResultsResponseData struct {
	BatchID        string `json:"batchId" url:"batchId"`
	Status         string `json:"status" url:"status"`
	TotalItems     *int   `json:"totalItems,omitempty" url:"totalItems,omitempty"`
	ProcessedItems *int   `json:"processedItems,omitempty" url:"processedItems,omitempty"`
	// Items where at least one phone was found
	Successful *int `json:"successful,omitempty" url:"successful,omitempty"`
	// Items where no phone was found or the lookup errored
	Failed  *int                   `json:"failed,omitempty" url:"failed,omitempty"`
	Results []*PhoneBulkResultItem `json:"results,omitempty" url:"results,omitempty"`
	Page    *int                   `json:"page,omitempty" url:"page,omitempty"`
	Limit   *int                   `json:"limit,omitempty" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneBulkJobResultsResponseData) GetBatchID() string {
	if p == nil {
		return ""
	}
	return p.BatchID
}

func (p *PhoneBulkJobResultsResponseData) GetStatus() string {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *PhoneBulkJobResultsResponseData) GetTotalItems() *int {
	if p == nil {
		return nil
	}
	return p.TotalItems
}

func (p *PhoneBulkJobResultsResponseData) GetProcessedItems() *int {
	if p == nil {
		return nil
	}
	return p.ProcessedItems
}

func (p *PhoneBulkJobResultsResponseData) GetSuccessful() *int {
	if p == nil {
		return nil
	}
	return p.Successful
}

func (p *PhoneBulkJobResultsResponseData) GetFailed() *int {
	if p == nil {
		return nil
	}
	return p.Failed
}

func (p *PhoneBulkJobResultsResponseData) GetResults() []*PhoneBulkResultItem {
	if p == nil {
		return nil
	}
	return p.Results
}

func (p *PhoneBulkJobResultsResponseData) GetPage() *int {
	if p == nil {
		return nil
	}
	return p.Page
}

func (p *PhoneBulkJobResultsResponseData) GetLimit() *int {
	if p == nil {
		return nil
	}
	return p.Limit
}

func (p *PhoneBulkJobResultsResponseData) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PhoneBulkJobResultsResponseData) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetBatchID sets the BatchID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobResultsResponseData) SetBatchID(batchID string) {
	p.BatchID = batchID
	p.require(phoneBulkJobResultsResponseDataFieldBatchID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobResultsResponseData) SetStatus(status string) {
	p.Status = status
	p.require(phoneBulkJobResultsResponseDataFieldStatus)
}

// SetTotalItems sets the TotalItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobResultsResponseData) SetTotalItems(totalItems *int) {
	p.TotalItems = totalItems
	p.require(phoneBulkJobResultsResponseDataFieldTotalItems)
}

// SetProcessedItems sets the ProcessedItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobResultsResponseData) SetProcessedItems(processedItems *int) {
	p.ProcessedItems = processedItems
	p.require(phoneBulkJobResultsResponseDataFieldProcessedItems)
}

// SetSuccessful sets the Successful field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobResultsResponseData) SetSuccessful(successful *int) {
	p.Successful = successful
	p.require(phoneBulkJobResultsResponseDataFieldSuccessful)
}

// SetFailed sets the Failed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobResultsResponseData) SetFailed(failed *int) {
	p.Failed = failed
	p.require(phoneBulkJobResultsResponseDataFieldFailed)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobResultsResponseData) SetResults(results []*PhoneBulkResultItem) {
	p.Results = results
	p.require(phoneBulkJobResultsResponseDataFieldResults)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobResultsResponseData) SetPage(page *int) {
	p.Page = page
	p.require(phoneBulkJobResultsResponseDataFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobResultsResponseData) SetLimit(limit *int) {
	p.Limit = limit
	p.require(phoneBulkJobResultsResponseDataFieldLimit)
}

func (p *PhoneBulkJobResultsResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneBulkJobResultsResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneBulkJobResultsResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneBulkJobResultsResponseData) MarshalJSON() ([]byte, error) {
	type embed PhoneBulkJobResultsResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneBulkJobResultsResponseData) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	phoneBulkJobStatusDataFieldBatchID        = big.NewInt(1 << 0)
	phoneBulkJobStatusDataFieldStatus         = big.NewInt(1 << 1)
	phoneBulkJobStatusDataFieldTotalItems     = big.NewInt(1 << 2)
	phoneBulkJobStatusDataFieldProcessedItems = big.NewInt(1 << 3)
	phoneBulkJobStatusDataFieldProgress       = big.NewInt(1 << 4)
)

type PhoneBulkJobStatusData struct {
	BatchID        string `json:"batchId" url:"batchId"`
	Status         string `json:"status" url:"status"`
	TotalItems     *int   `json:"totalItems,omitempty" url:"totalItems,omitempty"`
	ProcessedItems *int   `json:"processedItems,omitempty" url:"processedItems,omitempty"`
	// Completion percentage (0–100)
	Progress *float64 `json:"progress,omitempty" url:"progress,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneBulkJobStatusData) GetBatchID() string {
	if p == nil {
		return ""
	}
	return p.BatchID
}

func (p *PhoneBulkJobStatusData) GetStatus() string {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *PhoneBulkJobStatusData) GetTotalItems() *int {
	if p == nil {
		return nil
	}
	return p.TotalItems
}

func (p *PhoneBulkJobStatusData) GetProcessedItems() *int {
	if p == nil {
		return nil
	}
	return p.ProcessedItems
}

func (p *PhoneBulkJobStatusData) GetProgress() *float64 {
	if p == nil {
		return nil
	}
	return p.Progress
}

func (p *PhoneBulkJobStatusData) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PhoneBulkJobStatusData) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetBatchID sets the BatchID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobStatusData) SetBatchID(batchID string) {
	p.BatchID = batchID
	p.require(phoneBulkJobStatusDataFieldBatchID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobStatusData) SetStatus(status string) {
	p.Status = status
	p.require(phoneBulkJobStatusDataFieldStatus)
}

// SetTotalItems sets the TotalItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobStatusData) SetTotalItems(totalItems *int) {
	p.TotalItems = totalItems
	p.require(phoneBulkJobStatusDataFieldTotalItems)
}

// SetProcessedItems sets the ProcessedItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobStatusData) SetProcessedItems(processedItems *int) {
	p.ProcessedItems = processedItems
	p.require(phoneBulkJobStatusDataFieldProcessedItems)
}

// SetProgress sets the Progress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobStatusData) SetProgress(progress *float64) {
	p.Progress = progress
	p.require(phoneBulkJobStatusDataFieldProgress)
}

func (p *PhoneBulkJobStatusData) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneBulkJobStatusData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneBulkJobStatusData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneBulkJobStatusData) MarshalJSON() ([]byte, error) {
	type embed PhoneBulkJobStatusData
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneBulkJobStatusData) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	phoneBulkJobStatusResponseFieldData = big.NewInt(1 << 0)
	phoneBulkJobStatusResponseFieldMeta = big.NewInt(1 << 1)
)

type PhoneBulkJobStatusResponse struct {
	Data *PhoneBulkJobStatusData         `json:"data" url:"data"`
	Meta *PhoneBulkJobStatusResponseMeta `json:"meta,omitempty" url:"meta,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	success        bool

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneBulkJobStatusResponse) GetData() *PhoneBulkJobStatusData {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PhoneBulkJobStatusResponse) GetMeta() *PhoneBulkJobStatusResponseMeta {
	if p == nil {
		return nil
	}
	return p.Meta
}

func (p *PhoneBulkJobStatusResponse) Success() bool {
	return p.success
}

func (p *PhoneBulkJobStatusResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PhoneBulkJobStatusResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobStatusResponse) SetData(data *PhoneBulkJobStatusData) {
	p.Data = data
	p.require(phoneBulkJobStatusResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobStatusResponse) SetMeta(meta *PhoneBulkJobStatusResponseMeta) {
	p.Meta = meta
	p.require(phoneBulkJobStatusResponseFieldMeta)
}

func (p *PhoneBulkJobStatusResponse) UnmarshalJSON(data []byte) error {
	type embed PhoneBulkJobStatusResponse
	var unmarshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PhoneBulkJobStatusResponse(unmarshaler.embed)
	if unmarshaler.Success != true {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", p, true, unmarshaler.Success)
	}
	p.success = unmarshaler.Success
	extraProperties, err := internal.ExtractExtraProperties(data, *p, "success")
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneBulkJobStatusResponse) MarshalJSON() ([]byte, error) {
	type embed PhoneBulkJobStatusResponse
	var marshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed:   embed(*p),
		Success: true,
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneBulkJobStatusResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	phoneBulkJobStatusResponseMetaFieldRequestID = big.NewInt(1 << 0)
)

type PhoneBulkJobStatusResponseMeta struct {
	RequestID *string `json:"requestId,omitempty" url:"requestId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneBulkJobStatusResponseMeta) GetRequestID() *string {
	if p == nil {
		return nil
	}
	return p.RequestID
}

func (p *PhoneBulkJobStatusResponseMeta) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PhoneBulkJobStatusResponseMeta) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobStatusResponseMeta) SetRequestID(requestID *string) {
	p.RequestID = requestID
	p.require(phoneBulkJobStatusResponseMetaFieldRequestID)
}

func (p *PhoneBulkJobStatusResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneBulkJobStatusResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneBulkJobStatusResponseMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneBulkJobStatusResponseMeta) MarshalJSON() ([]byte, error) {
	type embed PhoneBulkJobStatusResponseMeta
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneBulkJobStatusResponseMeta) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Returned when you submit a bulk phone lookup job
var (
	phoneBulkJobSubmitDataFieldBatchID           = big.NewInt(1 << 0)
	phoneBulkJobSubmitDataFieldStatus            = big.NewInt(1 << 1)
	phoneBulkJobSubmitDataFieldItemCount         = big.NewInt(1 << 2)
	phoneBulkJobSubmitDataFieldMessage           = big.NewInt(1 << 3)
	phoneBulkJobSubmitDataFieldOriginalCount     = big.NewInt(1 << 4)
	phoneBulkJobSubmitDataFieldDuplicatesRemoved = big.NewInt(1 << 5)
)

type PhoneBulkJobSubmitData struct {
	// The job identifier — use it to poll status and fetch results
	BatchID string `json:"batchId" url:"batchId"`
	Status  string `json:"status" url:"status"`
	// Unique items in the job (after deduplication)
	ItemCount int     `json:"itemCount" url:"itemCount"`
	Message   *string `json:"message,omitempty" url:"message,omitempty"`
	// How many items you submitted before deduplication
	OriginalCount *int `json:"originalCount,omitempty" url:"originalCount,omitempty"`
	// How many duplicates were removed
	DuplicatesRemoved *int `json:"duplicatesRemoved,omitempty" url:"duplicatesRemoved,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneBulkJobSubmitData) GetBatchID() string {
	if p == nil {
		return ""
	}
	return p.BatchID
}

func (p *PhoneBulkJobSubmitData) GetStatus() string {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *PhoneBulkJobSubmitData) GetItemCount() int {
	if p == nil {
		return 0
	}
	return p.ItemCount
}

func (p *PhoneBulkJobSubmitData) GetMessage() *string {
	if p == nil {
		return nil
	}
	return p.Message
}

func (p *PhoneBulkJobSubmitData) GetOriginalCount() *int {
	if p == nil {
		return nil
	}
	return p.OriginalCount
}

func (p *PhoneBulkJobSubmitData) GetDuplicatesRemoved() *int {
	if p == nil {
		return nil
	}
	return p.DuplicatesRemoved
}

func (p *PhoneBulkJobSubmitData) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PhoneBulkJobSubmitData) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetBatchID sets the BatchID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobSubmitData) SetBatchID(batchID string) {
	p.BatchID = batchID
	p.require(phoneBulkJobSubmitDataFieldBatchID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobSubmitData) SetStatus(status string) {
	p.Status = status
	p.require(phoneBulkJobSubmitDataFieldStatus)
}

// SetItemCount sets the ItemCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobSubmitData) SetItemCount(itemCount int) {
	p.ItemCount = itemCount
	p.require(phoneBulkJobSubmitDataFieldItemCount)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobSubmitData) SetMessage(message *string) {
	p.Message = message
	p.require(phoneBulkJobSubmitDataFieldMessage)
}

// SetOriginalCount sets the OriginalCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobSubmitData) SetOriginalCount(originalCount *int) {
	p.OriginalCount = originalCount
	p.require(phoneBulkJobSubmitDataFieldOriginalCount)
}

// SetDuplicatesRemoved sets the DuplicatesRemoved field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobSubmitData) SetDuplicatesRemoved(duplicatesRemoved *int) {
	p.DuplicatesRemoved = duplicatesRemoved
	p.require(phoneBulkJobSubmitDataFieldDuplicatesRemoved)
}

func (p *PhoneBulkJobSubmitData) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneBulkJobSubmitData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneBulkJobSubmitData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneBulkJobSubmitData) MarshalJSON() ([]byte, error) {
	type embed PhoneBulkJobSubmitData
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneBulkJobSubmitData) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	phoneBulkJobSubmitResponseFieldData = big.NewInt(1 << 0)
	phoneBulkJobSubmitResponseFieldMeta = big.NewInt(1 << 1)
)

type PhoneBulkJobSubmitResponse struct {
	Data *PhoneBulkJobSubmitData `json:"data" url:"data"`
	Meta *BatchSubmitMeta        `json:"meta,omitempty" url:"meta,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	success        bool

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneBulkJobSubmitResponse) GetData() *PhoneBulkJobSubmitData {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PhoneBulkJobSubmitResponse) GetMeta() *BatchSubmitMeta {
	if p == nil {
		return nil
	}
	return p.Meta
}

func (p *PhoneBulkJobSubmitResponse) Success() bool {
	return p.success
}

func (p *PhoneBulkJobSubmitResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PhoneBulkJobSubmitResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobSubmitResponse) SetData(data *PhoneBulkJobSubmitData) {
	p.Data = data
	p.require(phoneBulkJobSubmitResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkJobSubmitResponse) SetMeta(meta *BatchSubmitMeta) {
	p.Meta = meta
	p.require(phoneBulkJobSubmitResponseFieldMeta)
}

func (p *PhoneBulkJobSubmitResponse) UnmarshalJSON(data []byte) error {
	type embed PhoneBulkJobSubmitResponse
	var unmarshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PhoneBulkJobSubmitResponse(unmarshaler.embed)
	if unmarshaler.Success != true {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", p, true, unmarshaler.Success)
	}
	p.success = unmarshaler.Success
	extraProperties, err := internal.ExtractExtraProperties(data, *p, "success")
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneBulkJobSubmitResponse) MarshalJSON() ([]byte, error) {
	type embed PhoneBulkJobSubmitResponse
	var marshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed:   embed(*p),
		Success: true,
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneBulkJobSubmitResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// One result from a bulk phone lookup
var (
	phoneBulkResultItemFieldEmail    = big.NewInt(1 << 0)
	phoneBulkResultItemFieldLinkedin = big.NewInt(1 << 1)
	phoneBulkResultItemFieldPhones   = big.NewInt(1 << 2)
	phoneBulkResultItemFieldError    = big.NewInt(1 << 3)
)

type PhoneBulkResultItem struct {
	// The email address that was looked up (if the item was an email)
	Email *string `json:"email,omitempty" url:"email,omitempty"`
	// The profile URL that was looked up (if the item was a profile URL)
	Linkedin *string `json:"linkedin,omitempty" url:"linkedin,omitempty"`
	// Phone numbers found for this person (empty if none found)
	Phones []string `json:"phones,omitempty" url:"phones,omitempty"`
	// An error message if the lookup failed for this item
	Error *string `json:"error,omitempty" url:"error,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneBulkResultItem) GetEmail() *string {
	if p == nil {
		return nil
	}
	return p.Email
}

func (p *PhoneBulkResultItem) GetLinkedin() *string {
	if p == nil {
		return nil
	}
	return p.Linkedin
}

func (p *PhoneBulkResultItem) GetPhones() []string {
	if p == nil {
		return nil
	}
	return p.Phones
}

func (p *PhoneBulkResultItem) GetError() *string {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PhoneBulkResultItem) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PhoneBulkResultItem) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkResultItem) SetEmail(email *string) {
	p.Email = email
	p.require(phoneBulkResultItemFieldEmail)
}

// SetLinkedin sets the Linkedin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkResultItem) SetLinkedin(linkedin *string) {
	p.Linkedin = linkedin
	p.require(phoneBulkResultItemFieldLinkedin)
}

// SetPhones sets the Phones field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkResultItem) SetPhones(phones []string) {
	p.Phones = phones
	p.require(phoneBulkResultItemFieldPhones)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneBulkResultItem) SetError(error_ *string) {
	p.Error = error_
	p.require(phoneBulkResultItemFieldError)
}

func (p *PhoneBulkResultItem) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneBulkResultItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneBulkResultItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneBulkResultItem) MarshalJSON() ([]byte, error) {
	type embed PhoneBulkResultItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneBulkResultItem) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	phoneLookupResponseFieldData = big.NewInt(1 << 0)
	phoneLookupResponseFieldMeta = big.NewInt(1 << 1)
)

type PhoneLookupResponse struct {
	Data *PhoneLookupResult `json:"data" url:"data"`
	Meta *EnrichmentMeta    `json:"meta,omitempty" url:"meta,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	success        bool

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneLookupResponse) GetData() *PhoneLookupResult {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PhoneLookupResponse) GetMeta() *EnrichmentMeta {
	if p == nil {
		return nil
	}
	return p.Meta
}

func (p *PhoneLookupResponse) Success() bool {
	return p.success
}

func (p *PhoneLookupResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PhoneLookupResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneLookupResponse) SetData(data *PhoneLookupResult) {
	p.Data = data
	p.require(phoneLookupResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneLookupResponse) SetMeta(meta *EnrichmentMeta) {
	p.Meta = meta
	p.require(phoneLookupResponseFieldMeta)
}

func (p *PhoneLookupResponse) UnmarshalJSON(data []byte) error {
	type embed PhoneLookupResponse
	var unmarshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PhoneLookupResponse(unmarshaler.embed)
	if unmarshaler.Success != true {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", p, true, unmarshaler.Success)
	}
	p.success = unmarshaler.Success
	extraProperties, err := internal.ExtractExtraProperties(data, *p, "success")
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneLookupResponse) MarshalJSON() ([]byte, error) {
	type embed PhoneLookupResponse
	var marshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed:   embed(*p),
		Success: true,
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneLookupResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	phoneLookupResultFieldPhones = big.NewInt(1 << 0)
)

type PhoneLookupResult struct {
	// The phone numbers we found
	Phones []string `json:"phones" url:"phones"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhoneLookupResult) GetPhones() []string {
	if p == nil {
		return nil
	}
	return p.Phones
}

func (p *PhoneLookupResult) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PhoneLookupResult) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPhones sets the Phones field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneLookupResult) SetPhones(phones []string) {
	p.Phones = phones
	p.require(phoneLookupResultFieldPhones)
}

func (p *PhoneLookupResult) UnmarshalJSON(data []byte) error {
	type unmarshaler PhoneLookupResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhoneLookupResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneLookupResult) MarshalJSON() ([]byte, error) {
	type embed PhoneLookupResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhoneLookupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
