// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "github.com/maximiseai/enrich-go-sdk/internal"
	time "time"
)

var (
	getWalletTransactionsRequestFieldPage  = big.NewInt(1 << 0)
	getWalletTransactionsRequestFieldLimit = big.NewInt(1 << 1)
	getWalletTransactionsRequestFieldType  = big.NewInt(1 << 2)
)

type GetWalletTransactionsRequest struct {
	// Page number (default: 1)
	Page *int `json:"-" url:"page,omitempty"`
	// Items per page (default: 50, max: 100)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Filter by type: `deduction`, `topup`, `adjustment`, or `refund`
	Type *string `json:"-" url:"type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetWalletTransactionsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetWalletTransactionsRequest) SetPage(page *int) {
	g.Page = page
	g.require(getWalletTransactionsRequestFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetWalletTransactionsRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getWalletTransactionsRequestFieldLimit)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetWalletTransactionsRequest) SetType(type_ *string) {
	g.Type = type_
	g.require(getWalletTransactionsRequestFieldType)
}

var (
	paginationFieldPage       = big.NewInt(1 << 0)
	paginationFieldLimit      = big.NewInt(1 << 1)
	paginationFieldTotal      = big.NewInt(1 << 2)
	paginationFieldTotalPages = big.NewInt(1 << 3)
)

type Pagination struct {
	// The page you're on
	Page int `json:"page" url:"page"`
	// Items per page
	Limit int `json:"limit" url:"limit"`
	// Total items across all pages
	Total int `json:"total" url:"total"`
	// Total number of pages
	TotalPages int `json:"totalPages" url:"totalPages"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *Pagination) GetPage() int {
	if p == nil {
		return 0
	}
	return p.Page
}

func (p *Pagination) GetLimit() int {
	if p == nil {
		return 0
	}
	return p.Limit
}

func (p *Pagination) GetTotal() int {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *Pagination) GetTotalPages() int {
	if p == nil {
		return 0
	}
	return p.TotalPages
}

func (p *Pagination) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *Pagination) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Pagination) SetPage(page int) {
	p.Page = page
	p.require(paginationFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Pagination) SetLimit(limit int) {
	p.Limit = limit
	p.require(paginationFieldLimit)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Pagination) SetTotal(total int) {
	p.Total = total
	p.require(paginationFieldTotal)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Pagination) SetTotalPages(totalPages int) {
	p.TotalPages = totalPages
	p.require(paginationFieldTotalPages)
}

func (p *Pagination) UnmarshalJSON(data []byte) error {
	type unmarshaler Pagination
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = Pagination(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *Pagination) MarshalJSON() ([]byte, error) {
	type embed Pagination
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *Pagination) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	walletBalanceFieldOrganizationID = big.NewInt(1 << 0)
	walletBalanceFieldBalance        = big.NewInt(1 << 1)
	walletBalanceFieldAsOf           = big.NewInt(1 << 2)
)

type WalletBalance struct {
	// Your organization ID
	OrganizationID string `json:"organizationId" url:"organizationId"`
	// Your current credit balance
	Balance float64 `json:"balance" url:"balance"`
	// When this balance was last calculated
	AsOf time.Time `json:"asOf" url:"asOf"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	currency       string

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WalletBalance) GetOrganizationID() string {
	if w == nil {
		return ""
	}
	return w.OrganizationID
}

func (w *WalletBalance) GetBalance() float64 {
	if w == nil {
		return 0
	}
	return w.Balance
}

func (w *WalletBalance) GetAsOf() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.AsOf
}

func (w *WalletBalance) Currency() string {
	return w.currency
}

func (w *WalletBalance) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WalletBalance) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletBalance) SetOrganizationID(organizationID string) {
	w.OrganizationID = organizationID
	w.require(walletBalanceFieldOrganizationID)
}

// SetBalance sets the Balance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletBalance) SetBalance(balance float64) {
	w.Balance = balance
	w.require(walletBalanceFieldBalance)
}

// SetAsOf sets the AsOf field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletBalance) SetAsOf(asOf time.Time) {
	w.AsOf = asOf
	w.require(walletBalanceFieldAsOf)
}

func (w *WalletBalance) UnmarshalJSON(data []byte) error {
	type embed WalletBalance
	var unmarshaler = struct {
		embed
		AsOf     *internal.DateTime `json:"asOf"`
		Currency string             `json:"currency"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WalletBalance(unmarshaler.embed)
	w.AsOf = unmarshaler.AsOf.Time()
	if unmarshaler.Currency != "credits" {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", w, "credits", unmarshaler.Currency)
	}
	w.currency = unmarshaler.Currency
	extraProperties, err := internal.ExtractExtraProperties(data, *w, "currency")
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WalletBalance) MarshalJSON() ([]byte, error) {
	type embed WalletBalance
	var marshaler = struct {
		embed
		AsOf     *internal.DateTime `json:"asOf"`
		Currency string             `json:"currency"`
	}{
		embed:    embed(*w),
		AsOf:     internal.NewDateTime(w.AsOf),
		Currency: "credits",
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WalletBalance) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	walletBalanceResponseFieldData = big.NewInt(1 << 0)
)

type WalletBalanceResponse struct {
	Data *WalletBalance `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	success        bool

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WalletBalanceResponse) GetData() *WalletBalance {
	if w == nil {
		return nil
	}
	return w.Data
}

func (w *WalletBalanceResponse) Success() bool {
	return w.success
}

func (w *WalletBalanceResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WalletBalanceResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletBalanceResponse) SetData(data *WalletBalance) {
	w.Data = data
	w.require(walletBalanceResponseFieldData)
}

func (w *WalletBalanceResponse) UnmarshalJSON(data []byte) error {
	type embed WalletBalanceResponse
	var unmarshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WalletBalanceResponse(unmarshaler.embed)
	if unmarshaler.Success != true {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", w, true, unmarshaler.Success)
	}
	w.success = unmarshaler.Success
	extraProperties, err := internal.ExtractExtraProperties(data, *w, "success")
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WalletBalanceResponse) MarshalJSON() ([]byte, error) {
	type embed WalletBalanceResponse
	var marshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed:   embed(*w),
		Success: true,
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WalletBalanceResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	walletTransactionFieldID             = big.NewInt(1 << 0)
	walletTransactionFieldOrganizationID = big.NewInt(1 << 1)
	walletTransactionFieldType           = big.NewInt(1 << 2)
	walletTransactionFieldAmount         = big.NewInt(1 << 3)
	walletTransactionFieldBalanceAfter   = big.NewInt(1 << 4)
	walletTransactionFieldDescription    = big.NewInt(1 << 5)
	walletTransactionFieldMetadata       = big.NewInt(1 << 6)
	walletTransactionFieldCreatedAt      = big.NewInt(1 << 7)
)

type WalletTransaction struct {
	// Transaction ID
	ID             string `json:"id" url:"id"`
	OrganizationID string `json:"organizationId" url:"organizationId"`
	// One of: `deduction`, `topup`, `adjustment`, or `refund`
	Type string `json:"type" url:"type"`
	// The credit amount (negative for deductions, positive for top-ups and refunds)
	Amount float64 `json:"amount" url:"amount"`
	// Your balance after this transaction
	BalanceAfter float64 `json:"balanceAfter" url:"balanceAfter"`
	// A short note about what happened
	Description string `json:"description" url:"description"`
	// Additional context (varies by transaction type)
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	// When this transaction happened
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WalletTransaction) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *WalletTransaction) GetOrganizationID() string {
	if w == nil {
		return ""
	}
	return w.OrganizationID
}

func (w *WalletTransaction) GetType() string {
	if w == nil {
		return ""
	}
	return w.Type
}

func (w *WalletTransaction) GetAmount() float64 {
	if w == nil {
		return 0
	}
	return w.Amount
}

func (w *WalletTransaction) GetBalanceAfter() float64 {
	if w == nil {
		return 0
	}
	return w.BalanceAfter
}

func (w *WalletTransaction) GetDescription() string {
	if w == nil {
		return ""
	}
	return w.Description
}

func (w *WalletTransaction) GetMetadata() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.Metadata
}

func (w *WalletTransaction) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *WalletTransaction) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WalletTransaction) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTransaction) SetID(id string) {
	w.ID = id
	w.require(walletTransactionFieldID)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTransaction) SetOrganizationID(organizationID string) {
	w.OrganizationID = organizationID
	w.require(walletTransactionFieldOrganizationID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTransaction) SetType(type_ string) {
	w.Type = type_
	w.require(walletTransactionFieldType)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTransaction) SetAmount(amount float64) {
	w.Amount = amount
	w.require(walletTransactionFieldAmount)
}

// SetBalanceAfter sets the BalanceAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTransaction) SetBalanceAfter(balanceAfter float64) {
	w.BalanceAfter = balanceAfter
	w.require(walletTransactionFieldBalanceAfter)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTransaction) SetDescription(description string) {
	w.Description = description
	w.require(walletTransactionFieldDescription)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTransaction) SetMetadata(metadata map[string]interface{}) {
	w.Metadata = metadata
	w.require(walletTransactionFieldMetadata)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTransaction) SetCreatedAt(createdAt time.Time) {
	w.CreatedAt = createdAt
	w.require(walletTransactionFieldCreatedAt)
}

func (w *WalletTransaction) UnmarshalJSON(data []byte) error {
	type embed WalletTransaction
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WalletTransaction(unmarshaler.embed)
	w.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WalletTransaction) MarshalJSON() ([]byte, error) {
	type embed WalletTransaction
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed:     embed(*w),
		CreatedAt: internal.NewDateTime(w.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WalletTransaction) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	walletTransactionsResponseFieldData = big.NewInt(1 << 0)
)

type WalletTransactionsResponse struct {
	Data *WalletTransactionsResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	success        bool

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WalletTransactionsResponse) GetData() *WalletTransactionsResponseData {
	if w == nil {
		return nil
	}
	return w.Data
}

func (w *WalletTransactionsResponse) Success() bool {
	return w.success
}

func (w *WalletTransactionsResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WalletTransactionsResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTransactionsResponse) SetData(data *WalletTransactionsResponseData) {
	w.Data = data
	w.require(walletTransactionsResponseFieldData)
}

func (w *WalletTransactionsResponse) UnmarshalJSON(data []byte) error {
	type embed WalletTransactionsResponse
	var unmarshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WalletTransactionsResponse(unmarshaler.embed)
	if unmarshaler.Success != true {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", w, true, unmarshaler.Success)
	}
	w.success = unmarshaler.Success
	extraProperties, err := internal.ExtractExtraProperties(data, *w, "success")
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WalletTransactionsResponse) MarshalJSON() ([]byte, error) {
	type embed WalletTransactionsResponse
	var marshaler = struct {
		embed
		Success bool `json:"success"`
	}{
		embed:   embed(*w),
		Success: true,
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WalletTransactionsResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	walletTransactionsResponseDataFieldTransactions = big.NewInt(1 << 0)
	walletTransactionsResponseDataFieldPagination   = big.NewInt(1 << 1)
)

type WalletTransactionsResponseData struct {
	Transactions []*WalletTransaction `json:"transactions" url:"transactions"`
	Pagination   *Pagination          `json:"pagination" url:"pagination"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WalletTransactionsResponseData) GetTransactions() []*WalletTransaction {
	if w == nil {
		return nil
	}
	return w.Transactions
}

func (w *WalletTransactionsResponseData) GetPagination() *Pagination {
	if w == nil {
		return nil
	}
	return w.Pagination
}

func (w *WalletTransactionsResponseData) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WalletTransactionsResponseData) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetTransactions sets the Transactions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTransactionsResponseData) SetTransactions(transactions []*WalletTransaction) {
	w.Transactions = transactions
	w.require(walletTransactionsResponseDataFieldTransactions)
}

// SetPagination sets the Pagination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WalletTransactionsResponseData) SetPagination(pagination *Pagination) {
	w.Pagination = pagination
	w.require(walletTransactionsResponseDataFieldPagination)
}

func (w *WalletTransactionsResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler WalletTransactionsResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WalletTransactionsResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WalletTransactionsResponseData) MarshalJSON() ([]byte, error) {
	type embed WalletTransactionsResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WalletTransactionsResponseData) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}
