// Code generated by Fern. DO NOT EDIT.

package company_followers_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	sdk "github.com/maximiseai/enrich-go-sdk"
	client "github.com/maximiseai/enrich-go-sdk/client"
	option "github.com/maximiseai/enrich-go-sdk/option"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestCompanyFollowersStartCountEstimateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.CountEstimateRequest{
		CompanyURL: "https://linkedin.com/company/stripe",
		Departments: []sdk.CountEstimateRequestDepartmentsItem{
			sdk.CountEstimateRequestDepartmentsItemEngineering,
			sdk.CountEstimateRequestDepartmentsItemSales,
		},
	}
	_, invocationErr := client.CompanyFollowers.StartCountEstimate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCompanyFollowersStartCountEstimateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCompanyFollowersStartCountEstimateWithWireMock", "POST", "/count-estimate", nil, 1)
}

func TestCompanyFollowersGetCountEstimateStatusWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetCountEstimateStatusRequest{
		BatchID: "665b2a3f4c5d6e0013fgh002",
	}
	_, invocationErr := client.CompanyFollowers.GetCountEstimateStatus(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCompanyFollowersGetCountEstimateStatusWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCompanyFollowersGetCountEstimateStatusWithWireMock", "GET", "/count-estimate/665b2a3f4c5d6e0013fgh002", nil, 1)
}

func TestCompanyFollowersStartCompanyFollowerScrapeWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.CompanyFollowerRequest{
		CompanyURL: "https://linkedin.com/company/stripe",
		MaxLimit:   500,
	}
	_, invocationErr := client.CompanyFollowers.StartCompanyFollowerScrape(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCompanyFollowersStartCompanyFollowerScrapeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCompanyFollowersStartCompanyFollowerScrapeWithWireMock", "POST", "/company-follower", nil, 1)
}

func TestCompanyFollowersGetCompanyFollowerProgressWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetCompanyFollowerProgressRequest{
		BatchID: "665a1f4e2c3b7800129dce01",
	}
	_, invocationErr := client.CompanyFollowers.GetCompanyFollowerProgress(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCompanyFollowersGetCompanyFollowerProgressWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCompanyFollowersGetCompanyFollowerProgressWithWireMock", "GET", "/company-follower/665a1f4e2c3b7800129dce01/progress", nil, 1)
}

func TestCompanyFollowersGetCompanyFollowerResultsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetCompanyFollowerResultsRequest{
		BatchID: "665a1f4e2c3b7800129dce01",
	}
	_, invocationErr := client.CompanyFollowers.GetCompanyFollowerResults(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCompanyFollowersGetCompanyFollowerResultsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCompanyFollowersGetCompanyFollowerResultsWithWireMock", "GET", "/company-follower/665a1f4e2c3b7800129dce01/results", nil, 1)
}

func TestCompanyFollowersExportCompanyFollowerCsvWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.ExportCompanyFollowerCsvRequest{
		BatchID: "batchId",
	}
	_, invocationErr := client.CompanyFollowers.ExportCompanyFollowerCsv(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCompanyFollowersExportCompanyFollowerCsvWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCompanyFollowersExportCompanyFollowerCsvWithWireMock", "GET", "/company-follower/batchId/export", nil, 1)
}

func TestCompanyFollowersCheckCompanyFollowerLimitWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.CompanyFollowers.CheckCompanyFollowerLimit(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCompanyFollowersCheckCompanyFollowerLimitWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCompanyFollowersCheckCompanyFollowerLimitWithWireMock", "GET", "/company-follower/limit", nil, 1)
}
