// Code generated by Fern. DO NOT EDIT.

package reverse_email_lookup_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	sdk "github.com/maximiseai/enrich-go-sdk"
	client "github.com/maximiseai/enrich-go-sdk/client"
	option "github.com/maximiseai/enrich-go-sdk/option"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestReverseEmailLookupReverseLookupWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.LookupRequest{
		Email: "emily.zhang@figma.com",
	}
	_, invocationErr := client.ReverseEmailLookup.ReverseLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReverseEmailLookupReverseLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReverseEmailLookupReverseLookupWithWireMock", "POST", "/reverse-lookup/lookup", nil, 1)
}

func TestReverseEmailLookupBulkReverseLookupWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.BulkLookupRequest{
		Emails: []string{
			"emily.zhang@figma.com",
			"david.kim@vercel.com",
			"aisha.johnson@cloudflare.com",
		},
		WebhookURL: sdk.String(
			"https://api.yourapp.com/webhooks/enrich",
		),
	}
	_, invocationErr := client.ReverseEmailLookup.BulkReverseLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReverseEmailLookupBulkReverseLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReverseEmailLookupBulkReverseLookupWithWireMock", "POST", "/reverse-lookup/bulk-lookup", nil, 1)
}

func TestReverseEmailLookupGetBulkLookupStatusWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetBulkLookupStatusRequest{
		BatchID: "665a1f4e2c3b7800129dce01",
	}
	_, invocationErr := client.ReverseEmailLookup.GetBulkLookupStatus(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReverseEmailLookupGetBulkLookupStatusWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReverseEmailLookupGetBulkLookupStatusWithWireMock", "GET", "/reverse-lookup/bulk-lookup/665a1f4e2c3b7800129dce01", nil, 1)
}

func TestReverseEmailLookupGetBulkLookupResultsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetBulkLookupResultsRequest{
		BatchID: "665a1f4e2c3b7800129dce01",
	}
	_, invocationErr := client.ReverseEmailLookup.GetBulkLookupResults(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReverseEmailLookupGetBulkLookupResultsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReverseEmailLookupGetBulkLookupResultsWithWireMock", "GET", "/reverse-lookup/bulk-lookup/665a1f4e2c3b7800129dce01/results", nil, 1)
}
