// Code generated by Fern. DO NOT EDIT.

package leadfinder

import (
	context "context"
	sdk "github.com/maximiseai/enrich-go-sdk"
	core "github.com/maximiseai/enrich-go-sdk/core"
	internal "github.com/maximiseai/enrich-go-sdk/internal"
	option "github.com/maximiseai/enrich-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Search across people, companies, and insights dimensions with comprehensive filters. Returns combined person + org + insights data.
//
// **Free tier:**
// - First 75 results free (pages 1–3 at default page size of 25)
// - 50 free search queries per month
//
// **Paid tier (page 4+):**
// - 1 credit per result returned
// - Max 40 pages
//
// Results include preview fields only. Use the **Reveal** or **Enrich** endpoints to get email and phone.
//
// **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
func (c *Client) SearchLeads(
	ctx context.Context,
	request *sdk.LeadSearchRequest,
	opts ...option.RequestOption,
) (*sdk.LeadSearchResponse, error) {
	response, err := c.WithRawResponse.SearchLeads(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get the total count of leads matching your filters. This endpoint is free and does not consume credits.
//
// **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
func (c *Client) CountLeads(
	ctx context.Context,
	request *sdk.LeadCountRequest,
	opts ...option.RequestOption,
) (*sdk.LeadCountResponse, error) {
	response, err := c.WithRawResponse.CountLeads(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Export search results as a CSV file.
//
// **Pricing:**
// - Preview fields only: Free
// - `includeEmail`: 50 credits per lead
// - `includePhone`: 525 credits per lead
// - `includeNames`: 1 credit per lead (full last names)
// - `includeContactInfo`: Shorthand for email + phone (575 credits/lead)
//
// Previously revealed contacts are returned from cache at no additional cost. Credits are refunded for leads where contact info is unavailable.
//
// **Response:** Returns a CSV file (Content-Type: text/csv) with `X-Credits-Used` and `X-Credits-Refunded` headers.
//
// **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
func (c *Client) ExportLeads(
	ctx context.Context,
	request *sdk.LeadExportRequest,
	opts ...option.RequestOption,
) (*sdk.AsyncExportResponse, error) {
	response, err := c.WithRawResponse.ExportLeads(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// ListExportJobs lists recent CSV export jobs for the team (last 30 days).
// Supports pagination and optional status filtering.
// Requires approved Lead Finder access.
func (c *Client) ListExportJobs(
	ctx context.Context,
	request *sdk.ListExportJobsRequest,
	opts ...option.RequestOption,
) (*sdk.LeadExportJobListResponse, error) {
	response, err := c.WithRawResponse.ListExportJobs(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// GetExportJob polls the status of a CSV export job.
// Status is one of: pending, processing, completed, failed.
// Once completed, download via DownloadExportJob.
// Requires approved Lead Finder access.
func (c *Client) GetExportJob(
	ctx context.Context,
	jobID string,
	opts ...option.RequestOption,
) (*sdk.LeadExportJobStatusResponse, error) {
	response, err := c.WithRawResponse.GetExportJob(
		ctx,
		jobID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// DownloadExportJob streams the completed CSV for an export job.
// Returns an error if the job has not yet completed — poll GetExportJob first.
// Requires approved Lead Finder access.
func (c *Client) DownloadExportJob(
	ctx context.Context,
	jobID string,
	opts ...option.RequestOption,
) (string, error) {
	response, err := c.WithRawResponse.DownloadExportJob(
		ctx,
		jobID,
		opts...,
	)
	if err != nil {
		return "", err
	}
	return response.Body, nil
}

// Submit a reveal job for up to 25 leads. This endpoint is now async — it returns a job ticket immediately.
// Poll with GetRevealJob to get results when the job completes.
//
// Choose which fields to reveal via the optional `fields` parameter:
//
// - `["email"]` — 50 credits per lead
// - `["phone"]` — 525 credits per lead
// - `["email", "phone"]` — 575 credits per lead (default if omitted)
//
// Previously revealed contacts are returned from cache at no cost.
// Credits are charged asynchronously — insufficient credits will surface as a failed job.
//
// **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
func (c *Client) RevealLeads(
	ctx context.Context,
	request *sdk.LeadRevealRequest,
	opts ...option.RequestOption,
) (*sdk.RevealJobSubmitResponse, error) {
	response, err := c.WithRawResponse.RevealLeads(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Submit an enrich job for up to 25 leads. This endpoint is now async — it returns a job ticket immediately.
// Poll with GetRevealJob to get results when the job completes.
//
// **Pricing:**
// - Email: 50 credits per lead
// - Phone: 525 credits per lead
//
// Previously revealed fields are returned from cache at no cost.
// Credits are charged asynchronously — insufficient credits will surface as a failed job.
//
// **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
func (c *Client) EnrichLeads(
	ctx context.Context,
	request *sdk.LeadEnrichRequest,
	opts ...option.RequestOption,
) (*sdk.RevealJobSubmitResponse, error) {
	response, err := c.WithRawResponse.EnrichLeads(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Poll a single reveal/enrich job until complete. Returns the job status, progress, and results (when completed).
//
// Returns 404 if the job is not found or belongs to a different team.
func (c *Client) GetRevealJob(
	ctx context.Context,
	jobID string,
	opts ...option.RequestOption,
) (*sdk.RevealJobPollResponse, error) {
	response, err := c.WithRawResponse.GetRevealJob(
		ctx,
		jobID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// List recent reveal/enrich jobs for the team (last 30 days). Supports pagination and status filtering.
func (c *Client) ListRevealJobs(
	ctx context.Context,
	request *sdk.ListRevealJobsRequest,
	opts ...option.RequestOption,
) (*sdk.RevealJobListResponse, error) {
	response, err := c.WithRawResponse.ListRevealJobs(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Pay 1 credit per lead to unlock full last names. Search results mask last names by default; this endpoint reveals them.
//
// **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
func (c *Client) UnlockNames(
	ctx context.Context,
	request *sdk.UnlockNamesRequest,
	opts ...option.RequestOption,
) (*sdk.UnlockNamesResponse, error) {
	response, err := c.WithRawResponse.UnlockNames(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// List all saved searches for the current user. Free endpoint.
//
// **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
func (c *Client) ListSavedSearches(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.SavedSearchListResponse, error) {
	response, err := c.WithRawResponse.ListSavedSearches(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Save a search filter combination for reuse. Free endpoint.
//
// **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
func (c *Client) CreateSavedSearch(
	ctx context.Context,
	request *sdk.SavedSearchCreateRequest,
	opts ...option.RequestOption,
) (*sdk.SavedSearchResponse, error) {
	response, err := c.WithRawResponse.CreateSavedSearch(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a saved search by ID. Only the owner can delete their own saved searches.
//
// **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
func (c *Client) DeleteSavedSearch(
	ctx context.Context,
	request *sdk.DeleteSavedSearchRequest,
	opts ...option.RequestOption,
) (*sdk.LeadFinderDeletedResponse, error) {
	response, err := c.WithRawResponse.DeleteSavedSearch(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns available values for multi-select filter fields (countries, departments, industries, job functions, etc.). Values are fetched from the database and cached for performance. Free endpoint.
//
// **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
func (c *Client) GetFilterOptions(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.LeadFinderFilterOptionsResponse, error) {
	response, err := c.WithRawResponse.GetFilterOptions(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Prefix-based company name autocomplete. Returns matching company names for search typeahead. Free endpoint.
//
// **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
func (c *Client) SuggestCompanyNames(
	ctx context.Context,
	request *sdk.SuggestCompanyNamesRequest,
	opts ...option.RequestOption,
) (*sdk.LeadFinderSuggestResponse, error) {
	response, err := c.WithRawResponse.SuggestCompanyNames(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
