// Code generated by Fern. DO NOT EDIT.

package emailvalidation

import (
	context "context"
	sdk "github.com/maximiseai/enrich-go-sdk"
	core "github.com/maximiseai/enrich-go-sdk/core"
	internal "github.com/maximiseai/enrich-go-sdk/internal"
	option "github.com/maximiseai/enrich-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Checks whether an email address is deliverable. The response tells you the
// result (`valid`, `invalid`, or `risky`), the confidence level, the mail
// provider, and whether the domain is a catch-all.
//
// **Cost:** 1 credit. You are **not** charged if the result is `risky`.
func (c *Client) ValidateEmail(
	ctx context.Context,
	request *sdk.EmailValidationRequest,
	opts ...option.RequestOption,
) (*sdk.EmailValidationResponse, error) {
	response, err := c.WithRawResponse.ValidateEmail(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Submit up to **500 000 emails** in a single request. We automatically
// remove duplicates (case-insensitive) before processing, so you only pay
// for unique addresses.
//
// **Cost:** 1 credit per unique email, reserved when you submit. Any unused
// credits are refunded automatically when you fetch results.
//
// ### Webhook callbacks
//
// If you include a `webhookUrl`, your server will receive:
//
//  1. **A per-result callback** every time an individual email finishes
//     validation. See [emailValidationResult](#tag/Webhooks/operation/webhookEmailValidationResult)
//     for the exact payload.
//
//  2. **A completion callback** once every email in the batch has been
//     processed. See [emailValidationCompletion](#tag/Webhooks/operation/webhookEmailValidationCompletion)
//     for the exact payload.
func (c *Client) BatchValidateEmails(
	ctx context.Context,
	request *sdk.BatchEmailValidationRequest,
	opts ...option.RequestOption,
) (*sdk.BatchSubmitResponse, error) {
	response, err := c.WithRawResponse.BatchValidateEmails(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Poll this endpoint to see how your batch is doing. The `progress` field
// gives you a percentage, and `status` will be one of `queued`, `processing`,
// `completed`, or `failed`.
//
// **Cost:** Free — polling never costs credits.
func (c *Client) GetEmailValidationBatchStatus(
	ctx context.Context,
	request *sdk.GetEmailValidationBatchStatusRequest,
	opts ...option.RequestOption,
) (*sdk.BatchStatusResponse, error) {
	response, err := c.WithRawResponse.GetEmailValidationBatchStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Fetch the results once your batch has finished. Results are paginated — use
// `page` and `limit` to walk through them.
//
// **Credit settlement:** The first time you call this after the batch reaches
// `completed` or `failed`, we calculate the final cost and refund any excess
// credits. Subsequent calls return the cached settlement.
func (c *Client) GetEmailValidationBatchResults(
	ctx context.Context,
	request *sdk.GetEmailValidationBatchResultsRequest,
	opts ...option.RequestOption,
) (*sdk.EmailValidationBatchResultsResponse, error) {
	response, err := c.WithRawResponse.GetEmailValidationBatchResults(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
