// Code generated by Fern. DO NOT EDIT.

package peoplesearch

import (
	context "context"
	http "net/http"
	sdk "github.com/maximiseai/enrich-go-sdk"
	core "github.com/maximiseai/enrich-go-sdk/core"
	internal "github.com/maximiseai/enrich-go-sdk/internal"
	option "github.com/maximiseai/enrich-go-sdk/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) WaterfallIcpSearch(
	ctx context.Context,
	request *sdk.WaterfallIcpSearchRequest,
	opts ...option.RequestOption,
) (*core.Response[*sdk.WaterfallIcpSearchResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"",
	)
	endpointURL := baseURL + "/people-search/waterfall-icp-search"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *sdk.WaterfallIcpSearchResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sdk.WaterfallIcpSearchResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) EmployeeFinder(
	ctx context.Context,
	request *sdk.EmployeeFinderRequest,
	opts ...option.RequestOption,
) (*core.Response[*sdk.EmployeeFinderResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"",
	)
	endpointURL := baseURL + "/people-search/employee-finder"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *sdk.EmployeeFinderResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(sdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*sdk.EmployeeFinderResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
