// Code generated by Fern. DO NOT EDIT.

package companyfollowers

import (
	context "context"
	sdk "github.com/maximiseai/enrich-go-sdk"
	core "github.com/maximiseai/enrich-go-sdk/core"
	internal "github.com/maximiseai/enrich-go-sdk/internal"
	option "github.com/maximiseai/enrich-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// > **Access required** — This endpoint is available to approved accounts only. [Contact us](https://enrich.so) to request access.
//
// Starts an asynchronous count estimation job. Returns the estimated number of followers matching your filters, with optional breakdowns by department and seniority.
//
// **Cost:** 100 credits (fixed). Cached results for the same company + filters within 24 hours are free.
//
// **Results:** Poll the status endpoint to get results. Typically completes within 30–60 seconds.
func (c *Client) StartCountEstimate(
	ctx context.Context,
	request *sdk.CountEstimateRequest,
	opts ...option.RequestOption,
) (*sdk.StartCountEstimateResponse, error) {
	response, err := c.WithRawResponse.StartCountEstimate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// > **Access required** — This endpoint is available to approved accounts only. [Contact us](https://enrich.so) to request access.
//
// Check the status of a count estimation job and retrieve results when complete.
//
// **Cost:** Free — polling never costs credits.
//
// **Refunds:** If the job fails within 7 days, the 100 credits are refunded automatically on the next status check.
func (c *Client) GetCountEstimateStatus(
	ctx context.Context,
	request *sdk.GetCountEstimateStatusRequest,
	opts ...option.RequestOption,
) (*sdk.CountEstimateStatusResponse, error) {
	response, err := c.WithRawResponse.GetCountEstimateStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// > **Access required** — This endpoint is available to approved accounts only. [Contact us](https://enrich.so) to request access.
//
// Starts an asynchronous company follower scrape. Provide a company URL and a max_limit for how many profiles to retrieve.
//
// **Cost:** Credits per profile (see the /limit endpoint for your team's rate), reserved upfront based on max_limit. When you fetch results, we settle the bill — if fewer profiles were found, the excess credits are refunded automatically.
//
// **Filters:** Narrow results by country, job title, department, or seniority level.
//
// **Webhooks:** Optionally pass a `webhookUrl` to automatically receive one webhook per follower profile as it's scraped, plus a final completion callback when the job finishes. No separate flag needed — providing the URL enables per-result webhooks.
func (c *Client) StartCompanyFollowerScrape(
	ctx context.Context,
	request *sdk.CompanyFollowerRequest,
	opts ...option.RequestOption,
) (*sdk.StartCompanyFollowerResponse, error) {
	response, err := c.WithRawResponse.StartCompanyFollowerScrape(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// > **Access required** — This endpoint is available to approved accounts only. [Contact us](https://enrich.so) to request access.
//
// Poll this endpoint to track the progress of your company follower scrape.
//
// **Cost:** Free — polling never costs credits.
func (c *Client) GetCompanyFollowerProgress(
	ctx context.Context,
	request *sdk.GetCompanyFollowerProgressRequest,
	opts ...option.RequestOption,
) (*sdk.CompanyFollowerProgressResponse, error) {
	response, err := c.WithRawResponse.GetCompanyFollowerProgress(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// > **Access required** This endpoint is available to approved accounts only. [Contact us](https://enrich.so) to request access.
//
// Returns paginated follower profiles for a completed batch. Use `page` and `limit` query params to paginate through results.
//
// Credits are charged upfront when you start the scrape. If fewer profiles are found than `max_limit`, unused credits are refunded automatically.
//
// If you provided a `webhookUrl`, results are already delivered via webhooks and credits are auto-settled. No need to call this endpoint.
//
// Only call this after the progress endpoint reports `done: true`.
func (c *Client) GetCompanyFollowerResults(
	ctx context.Context,
	request *sdk.GetCompanyFollowerResultsRequest,
	opts ...option.RequestOption,
) (*sdk.CompanyFollowerResultsResponse, error) {
	response, err := c.WithRawResponse.GetCompanyFollowerResults(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// > **Access required** — This endpoint is available to approved accounts only. [Contact us](https://enrich.so) to request access.
//
// Download scrape results as a CSV file. Batch must be complete. No credits consumed.
func (c *Client) ExportCompanyFollowerCsv(
	ctx context.Context,
	request *sdk.ExportCompanyFollowerCsvRequest,
	opts ...option.RequestOption,
) (string, error) {
	response, err := c.WithRawResponse.ExportCompanyFollowerCsv(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return "", err
	}
	return response.Body, nil
}

// Check your team's daily company follower scraping limit and current usage. No credits consumed.
//
// **Possible statuses:**
// - `approved` — Team has access; `creditsPerProfile`, `dailyLimit`, `dailyUsed`, and `dailyRemaining` are included.
// - `pending` — Application is under review.
// - `rejected` — Application was rejected.
// - `revoked` — Access was revoked.
// - `none` — No application on file.
func (c *Client) CheckCompanyFollowerLimit(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.CheckCompanyFollowerLimitResponse, error) {
	response, err := c.WithRawResponse.CheckCompanyFollowerLimit(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
