// Code generated by Fern. DO NOT EDIT.

package phone_finder_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	sdk "github.com/maximiseai/enrich-go-sdk"
	client "github.com/maximiseai/enrich-go-sdk/client"
	option "github.com/maximiseai/enrich-go-sdk/option"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestPhoneFinderPhoneLookupWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.PhoneLookupRequest{
		Email: sdk.String(
			"sarah.chen@stripe.com",
		),
		Linkedin: sdk.String(
			"https://www.example.com/in/sarahchen",
		),
	}
	_, invocationErr := client.PhoneFinder.PhoneLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPhoneFinderPhoneLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPhoneFinderPhoneLookupWithWireMock", "GET", "/reverse-lookup/phones", map[string]string{"email": "sarah.chen@stripe.com", "linkedin": "https://www.example.com/in/sarahchen"}, 1)
}

func TestPhoneFinderCreatePhoneBulkJobWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.PhoneBatchRequest{
		Emails: []string{
			"sarah.chen@stripe.com",
			"james.rodriguez@hubspot.com",
		},
		Linkedins: []string{
			"https://www.example.com/in/priyapatel",
		},
		WebhookURL: sdk.String(
			"https://api.yourapp.com/webhooks/enrich",
		),
	}
	_, invocationErr := client.PhoneFinder.CreatePhoneBulkJob(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPhoneFinderCreatePhoneBulkJobWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPhoneFinderCreatePhoneBulkJobWithWireMock", "POST", "/reverse-lookup/phones/bulk", nil, 1)
}

func TestPhoneFinderGetPhoneBulkJobStatusWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetPhoneBulkJobStatusRequest{
		JobID: "665c52bf7b8e3f00149f0a10",
	}
	_, invocationErr := client.PhoneFinder.GetPhoneBulkJobStatus(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPhoneFinderGetPhoneBulkJobStatusWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPhoneFinderGetPhoneBulkJobStatusWithWireMock", "GET", "/reverse-lookup/phones/bulk/665c52bf7b8e3f00149f0a10", nil, 1)
}

func TestPhoneFinderGetPhoneBulkJobResultsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetPhoneBulkJobResultsRequest{
		JobID: "665c52bf7b8e3f00149f0a10",
	}
	_, invocationErr := client.PhoneFinder.GetPhoneBulkJobResults(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPhoneFinderGetPhoneBulkJobResultsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPhoneFinderGetPhoneBulkJobResultsWithWireMock", "GET", "/reverse-lookup/phones/bulk/665c52bf7b8e3f00149f0a10/results", nil, 1)
}
