// Code generated by Fern. DO NOT EDIT.

package emailfinder

import (
	context "context"
	sdk "github.com/maximiseai/enrich-go-sdk"
	core "github.com/maximiseai/enrich-go-sdk/core"
	internal "github.com/maximiseai/enrich-go-sdk/internal"
	option "github.com/maximiseai/enrich-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Give us a person's first name, last name, and their company domain, and we'll
// find their professional email address.
//
// **Cost:** 10 credits. You are **not** charged if we can't find an email
// (`found: false`).
func (c *Client) FindEmail(
	ctx context.Context,
	request *sdk.EmailFinderRequest,
	opts ...option.RequestOption,
) (*sdk.EmailFinderResponse, error) {
	response, err := c.WithRawResponse.FindEmail(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Submit up to **500 000 leads** in one request. Each lead is a combination
// of first name, last name, and domain. We deduplicate the list
// (case-insensitive) so you are only charged for unique leads.
//
// **Cost:** 10 credits per unique lead, reserved at submission. Unused credits
// are refunded when you fetch results.
//
// ### Webhook callbacks
//
// If you include a `webhookUrl`, your server will receive:
//
//  1. **A per-result callback** each time a single lead is processed. See
//     [emailFinderResult](#tag/Webhooks/operation/webhookEmailFinderResult) for the payload.
//
//  2. **A completion callback** once the entire batch is done. See
//     [emailFinderCompletion](#tag/Webhooks/operation/webhookEmailFinderCompletion) for the payload.
func (c *Client) BatchFindEmails(
	ctx context.Context,
	request *sdk.BatchEmailFinderRequest,
	opts ...option.RequestOption,
) (*sdk.BatchSubmitResponse, error) {
	response, err := c.WithRawResponse.BatchFindEmails(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Poll this endpoint to track your batch. The `status` moves through
// `queued` → `processing` → `completed` (or `failed`).
//
// **Cost:** Free.
func (c *Client) GetEmailFinderBatchStatus(
	ctx context.Context,
	request *sdk.GetEmailFinderBatchStatusRequest,
	opts ...option.RequestOption,
) (*sdk.BatchStatusResponse, error) {
	response, err := c.WithRawResponse.GetEmailFinderBatchStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the results once the batch has finished. Results are paginated.
//
// **Credit settlement:** On the first call after the batch reaches a terminal
// status, we settle the final credit charge. Leads where no email was found
// are not charged, and the difference is refunded.
func (c *Client) GetEmailFinderBatchResults(
	ctx context.Context,
	request *sdk.GetEmailFinderBatchResultsRequest,
	opts ...option.RequestOption,
) (*sdk.EmailFinderBatchResultsResponse, error) {
	response, err := c.WithRawResponse.GetEmailFinderBatchResults(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
